# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute if score @s aj.idle_angry.frame matches 41.. run scoreboard players set @s aj.idle_angry.frame 1
data remove storage aj:temp args
execute store result storage aj:temp args.frame int 1 run scoreboard players get @s aj.idle_angry.frame
execute at @s run function animated_java:copper_golem/animations/idle_angry/zzz/apply_frame with storage aj:temp args
scoreboard players add @s aj.idle_angry.frame 1