# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
tag @s remove aj.copper_golem.animation.idle_angry.playing
scoreboard players set @s aj.idle_angry.frame 0
tag @s add aj.transforms_only
execute at @s run function animated_java:copper_golem/animations/idle_angry/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only