# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:copper_golem/animations/idle_angry/zzz/apply_frame {frame: 40}
scoreboard players add @s aj.idle_angry.frame 1