# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute if score @s aj.action.frame matches 21.. run scoreboard players set @s aj.action.frame 1
data remove storage aj:temp args
execute store result storage aj:temp args.frame int 1 run scoreboard players get @s aj.action.frame
execute at @s run function animated_java:copper_golem/animations/action/zzz/apply_frame with storage aj:temp args
scoreboard players add @s aj.action.frame 1