# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute if score @s aj.exit_hide.frame matches 11.. run scoreboard players set @s aj.exit_hide.frame 1
data remove storage aj:temp args
execute store result storage aj:temp args.frame int 1 run scoreboard players get @s aj.exit_hide.frame
execute at @s run function animated_java:snail/animations/exit_hide/zzz/apply_frame with storage aj:temp args
scoreboard players add @s aj.exit_hide.frame 1