# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute if score @s aj.start_holding.frame matches 10.. run scoreboard players set @s aj.start_holding.frame 1
data remove storage aj:temp args
execute store result storage aj:temp args.frame int 1 run scoreboard players get @s aj.start_holding.frame
execute at @s run function animated_java:tuff_golem/animations/start_holding/zzz/apply_frame with storage aj:temp args
scoreboard players add @s aj.start_holding.frame 1