# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
tag @s add aj.tuff_golem.animation.start_holding.playing
scoreboard players set @s aj.start_holding.frame 0
tag @s add aj.transforms_only
execute at @s run function animated_java:tuff_golem/animations/start_holding/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only