# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.data_data set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.jellyfish.node.body] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_body set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.jellyfish.node.stingers_1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_stingers_1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.jellyfish.node.stingers_2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_stingers_2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.jellyfish.node.stingers_3] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_stingers_3 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.jellyfish.node.stingers_4] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_stingers_4 set from storage aj:uuid main.out