# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_head) {transformation: [-1f,0.0044f,0.0003f,0f,0.0044f,1f,-0.0044f,-0.3125f,-0.0004f,-0.0044f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_top) {transformation: [-1.005f,0f,0f,0f,0f,1.0025f,0f,-0.375f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_left) {transformation: [-1.005f,0f,0f,0f,0f,1.0025f,0f,-0.375f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_right) {transformation: [-1.005f,0f,0f,0f,0f,1.0025f,0f,-0.375f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}