# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.data_data set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.vulture.node.body2] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_body2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.vulture.node.body3] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_body3 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.vulture.node.head2] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_head2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.vulture.node.body] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_body set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.vulture.node.left_tip] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_left_tip set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.vulture.node.left_wing] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_left_wing set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.vulture.node.right_tip] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_right_tip set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.vulture.node.right_wing] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_right_wing set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.vulture.node.tail] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_tail set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.vulture.node.vulture] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_vulture set from storage aj:uuid main.out