# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.bloomer.root] run return 0
execute unless score @s aj.is_rig_loaded matches 1 run function #animated_java:global/root/on_load
function #animated_java:bloomer/as_root/pre_tick
execute if entity @s[tag=aj.bloomer.animation.idle.playing] run function animated_java:bloomer/animations/idle/zzz/on_tick
execute if entity @s[tag=aj.bloomer.animation.walk.playing] run function animated_java:bloomer/animations/walk/zzz/on_tick
execute if entity @s[tag=aj.bloomer.animation.explode.playing] run function animated_java:bloomer/animations/explode/zzz/on_tick
execute at @s on passengers run rotate @s ~ ~
function #animated_java:bloomer/as_root/post_tick