# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers if entity @s[tag=aj.copper_golem.bone.left_foot] run function animated_java:copper_golem/variants/default/zzz/apply_to_bone_left_foot
execute on passengers if entity @s[tag=aj.copper_golem.bone.right_foot] run function animated_java:copper_golem/variants/default/zzz/apply_to_bone_right_foot
execute on passengers if entity @s[tag=aj.copper_golem.bone.antenna] run function animated_java:copper_golem/variants/default/zzz/apply_to_bone_antenna
execute on passengers if entity @s[tag=aj.copper_golem.bone.nose] run function animated_java:copper_golem/variants/default/zzz/apply_to_bone_nose
execute on passengers if entity @s[tag=aj.copper_golem.bone.head] run function animated_java:copper_golem/variants/default/zzz/apply_to_bone_head
execute on passengers if entity @s[tag=aj.copper_golem.bone.left_arm] run function animated_java:copper_golem/variants/default/zzz/apply_to_bone_left_arm
execute on passengers if entity @s[tag=aj.copper_golem.bone.right_arm] run function animated_java:copper_golem/variants/default/zzz/apply_to_bone_right_arm
execute on passengers if entity @s[tag=aj.copper_golem.bone.body] run function animated_java:copper_golem/variants/default/zzz/apply_to_bone_body
return 1