# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.snail.root] run return 0
execute on passengers if entity @s[tag=aj.snail.data] unless data entity @s {data:{rigHash: 'd625b0184a9ed214ae709b863d07bae40fbcf7dca6afe043b8e8baa62abb417d'}} on vehicle run function animated_java:snail/root/zzz/0
scoreboard players set @s aj.is_rig_loaded 1