# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=minecraft:item_display,tag=aj.copper_golem.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'copper_golem', 'function_path': 'animated_java:copper_golem/animations/pause_all'}
tag @s remove aj.copper_golem.animation.idle.playing
tag @s remove aj.copper_golem.animation.idle_angry.playing
tag @s remove aj.copper_golem.animation.walk.playing
tag @s remove aj.copper_golem.animation.walk_angry.playing
tag @s remove aj.copper_golem.animation.action.playing