# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
tag @s remove aj.copper_golem.animation.idle.playing
tag @s remove aj.copper_golem.animation.idle_angry.playing
tag @s remove aj.copper_golem.animation.walk.playing
tag @s remove aj.copper_golem.animation.walk_angry.playing
tag @s remove aj.copper_golem.animation.action.playing