# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.tuff_golem.root] run return 0
execute if entity @s[tag=aj.tuff_golem.animation.idle.playing] run function animated_java:tuff_golem/animations/idle/zzz/on_tick
execute if entity @s[tag=aj.tuff_golem.animation.walk.playing] run function animated_java:tuff_golem/animations/walk/zzz/on_tick
execute if entity @s[tag=aj.tuff_golem.animation.start_holding.playing] run function animated_java:tuff_golem/animations/start_holding/zzz/on_tick
execute if entity @s[tag=aj.tuff_golem.animation.end_holding.playing] run function animated_java:tuff_golem/animations/end_holding/zzz/on_tick
#execute at @s on passengers run rotate @s ~ ~