# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute if score @s aj.dig.frame matches 81.. run scoreboard players set @s aj.dig.frame 1
data remove storage aj:temp args
execute store result storage aj:temp args.frame int 1 run scoreboard players get @s aj.dig.frame
execute at @s run function animated_java:nautilus_crab/animations/dig/zzz/apply_frame with storage aj:temp args
scoreboard players add @s aj.dig.frame 1