# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=minecraft:item_display,tag=aj.nautilus_crab.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'nautilus_crab', 'function_path': 'animated_java:nautilus_crab/animations/dig/stop'}
tag @s remove aj.nautilus_crab.animation.dig.playing
scoreboard players set @s aj.dig.frame 0
tag @s add aj.transforms_only
execute at @s run function animated_java:nautilus_crab/animations/dig/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only