# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
tag @s remove aj.nautilus_crab.animation.dig.playing
scoreboard players set @s aj.dig.frame 0
tag @s add aj.transforms_only
execute at @s run function animated_java:nautilus_crab/animations/dig/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only