# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.hedgehog.root] run return 0
execute on passengers if entity @s[tag=aj.hedgehog.data] unless data entity @s {data:{rigHash: '49b39e65a6713ff1834ac87f99bcda4d99c003c1ee2bb11e9975644e80ff087c'}} on vehicle run function animated_java:hedgehog/root/zzz/check_rig_hash
scoreboard players set @s aj.is_rig_loaded 1