# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.hedgehog.root] run return 0
execute unless score @s aj.is_rig_loaded matches 1 run function #animated_java:global/root/on_load
execute if entity @s[tag=aj.hedgehog.animation.walk.playing] run function animated_java:hedgehog/animations/walk/zzz/on_tick
execute if entity @s[tag=aj.hedgehog.animation.idle.playing] run function animated_java:hedgehog/animations/idle/zzz/on_tick
execute if entity @s[tag=aj.hedgehog.animation.hide.playing] run function animated_java:hedgehog/animations/hide/zzz/on_tick
execute at @s on passengers run rotate @s ~ ~