# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.nautilus_crab.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'nautilus_crab', 'function_path': 'animated_java:nautilus_crab/animations/dig/apply_frame'}
$execute store result storage aj:temp frame int 1 run scoreboard players set @s aj.dig.frame $(frame)
execute at @s run function animated_java:nautilus_crab/animations/dig/zzz/apply_frame with storage aj:temp