# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
tag @s remove aj.penguin.animation.idle.playing
tag @s remove aj.penguin.animation.walk.playing
tag @s remove aj.penguin.animation.fall.playing
tag @s remove aj.penguin.animation.bartering.playing