# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.nautilus_crab.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'nautilus_crab', 'function_path': 'animated_java:nautilus_crab/variants/pink/apply'}
execute on passengers if entity @s[tag=aj.nautilus_crab.bone.shell] run function animated_java:nautilus_crab/variants/pink/zzz/0
execute on passengers if entity @s[tag=aj.nautilus_crab.bone.body] run function animated_java:nautilus_crab/variants/pink/zzz/1
execute on passengers if entity @s[tag=aj.nautilus_crab.bone.left_claw] run function animated_java:nautilus_crab/variants/pink/zzz/2
execute on passengers if entity @s[tag=aj.nautilus_crab.bone.right_claw] run function animated_java:nautilus_crab/variants/pink/zzz/3
execute on passengers if entity @s[tag=aj.nautilus_crab.bone.left_legs] run function animated_java:nautilus_crab/variants/pink/zzz/4
execute on passengers if entity @s[tag=aj.nautilus_crab.bone.right_legs] run function animated_java:nautilus_crab/variants/pink/zzz/5