# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.snail.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'snail', 'function_path': 'animated_java:snail/variants/cyan/apply'}
execute on passengers if entity @s[tag=aj.snail.bone.head] run function animated_java:snail/variants/cyan/zzz/0
execute on passengers if entity @s[tag=aj.snail.bone.tail] run function animated_java:snail/variants/cyan/zzz/1
execute on passengers if entity @s[tag=aj.snail.bone.shell] run function animated_java:snail/variants/cyan/zzz/2
execute on passengers if entity @s[tag=aj.snail.bone.left_eye] run function animated_java:snail/variants/cyan/zzz/3
execute on passengers if entity @s[tag=aj.snail.bone.right_eye] run function animated_java:snail/variants/cyan/zzz/4