# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.butterfly.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'butterfly', 'function_path': 'animated_java:butterfly/variants/default_hurt/apply'}
execute on passengers if entity @s[tag=aj.butterfly.bone.body] run function animated_java:butterfly/variants/default_hurt/zzz/apply_to_bone_body
execute on passengers if entity @s[tag=aj.butterfly.bone.wing_1] run function animated_java:butterfly/variants/default_hurt/zzz/apply_to_bone_wing_1
execute on passengers if entity @s[tag=aj.butterfly.bone.wing_2] run function animated_java:butterfly/variants/default_hurt/zzz/apply_to_bone_wing_2
return 1