# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.data_data set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.pufftail.node.top_fin_3] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_top_fin_3 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.pufftail.node.top_fin_2] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_top_fin_2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.pufftail.node.top_fin_1] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_top_fin_1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.pufftail.node.body_front] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_body_front set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.pufftail.node.top_fin_4] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_top_fin_4 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.pufftail.node.top_fin_5] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_top_fin_5 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.pufftail.node.body_middle] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_body_middle set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.pufftail.node.top_fin_6] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_top_fin_6 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.pufftail.node.body_tail] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_body_tail set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.pufftail.node.back_right] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_back_right set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.pufftail.node.front_right] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_front_right set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.pufftail.node.front_left] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_front_left set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.pufftail.node.back_left] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_back_left set from storage aj:uuid main.out