# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_body2) {transformation: [-1f,0f,0f,0.125f,0f,0.6805f,0.7327f,-0.3546f,0f,0.7327f,-0.6805f,0.0704f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_body3) {transformation: [-1f,0f,0f,-0.125f,0f,0.6805f,0.7327f,-0.3546f,0f,0.7327f,-0.6805f,0.0704f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_head2) {transformation: [-1f,0f,0f,0f,0f,0.995f,0.1f,-0.134f,0f,0.1f,-0.995f,0.8495f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_left_tip) {transformation: [-0.9991f,0.0431f,0f,1.1742f,0.0431f,0.9991f,0f,-0.0368f,0f,0f,-1f,0.3125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_left_wing) {transformation: [-0.9999f,-0.0128f,0f,0.1731f,-0.0128f,0.9999f,0f,0.0481f,0f,0f,-1f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_right_tip) {transformation: [-0.9979f,-0.0642f,0f,-1.1722f,-0.0642f,0.9979f,0f,-0.0579f,0f,0f,-1f,0.3125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_right_wing) {transformation: [-1f,-0.0084f,0f,-0.1731f,-0.0084f,1f,0f,0.0481f,0f,0f,-1f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_tail) {transformation: [-1f,0f,0f,0f,0f,0.9999f,0.0134f,0.0625f,0f,0.0134f,-0.9999f,-0.0625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}