# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_body2) {transformation: [-1f,0f,0f,0.125f,0f,0.7142f,0.7f,-0.3546f,0f,0.7f,-0.7142f,0.0704f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_body3) {transformation: [-1f,0f,0f,-0.125f,0f,0.7142f,0.7f,-0.3546f,0f,0.7f,-0.7142f,0.0704f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_head2) {transformation: [-1f,0f,0f,0f,0f,0.987f,0.1609f,-0.1441f,0f,0.1609f,-0.987f,0.8495f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_left_tip) {transformation: [-0.8829f,0.4696f,0f,1.1225f,0.4696f,0.8829f,0f,-0.304f,0f,0f,-1f,0.3125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_left_wing) {transformation: [-0.9709f,0.2396f,0f,0.1815f,0.2396f,0.9709f,0f,0.0565f,0f,0f,-1f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_right_tip) {transformation: [-0.8771f,-0.4804f,0f,-1.1181f,-0.4804f,0.8771f,0f,-0.3155f,0f,0f,-1f,0.3125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_right_wing) {transformation: [-0.9679f,-0.2514f,0f,-0.1815f,-0.2514f,0.9679f,0f,0.0565f,0f,0f,-1f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_tail) {transformation: [-1f,0f,0f,0f,0f,0.9942f,0.1072f,0.0625f,0f,0.1072f,-0.9942f,-0.0625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}