# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.rat.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'rat', 'function_path': 'animated_java:rat/variants/gray/apply'}
execute on passengers if entity @s[tag=aj.rat.bone.body] run function animated_java:rat/variants/gray/zzz/0
execute on passengers if entity @s[tag=aj.rat.bone.head] run function animated_java:rat/variants/gray/zzz/1
execute on passengers if entity @s[tag=aj.rat.bone.1] run function animated_java:rat/variants/gray/zzz/2
execute on passengers if entity @s[tag=aj.rat.bone.2] run function animated_java:rat/variants/gray/zzz/3
execute on passengers if entity @s[tag=aj.rat.bone.3] run function animated_java:rat/variants/gray/zzz/4
execute on passengers if entity @s[tag=aj.rat.bone.4] run function animated_java:rat/variants/gray/zzz/5
execute on passengers if entity @s[tag=aj.rat.bone.back_left_foot] run function animated_java:rat/variants/gray/zzz/6
execute on passengers if entity @s[tag=aj.rat.bone.back_right_foot] run function animated_java:rat/variants/gray/zzz/7
execute on passengers if entity @s[tag=aj.rat.bone.front_right_foot] run function animated_java:rat/variants/gray/zzz/8
execute on passengers if entity @s[tag=aj.rat.bone.front_left_foot] run function animated_java:rat/variants/gray/zzz/9