# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.mushling.root] run return 0
execute on passengers if entity @s[tag=aj.mushling.data] unless data entity @s {data:{rigHash: 'c02990075987bb27d37f3c337fc95fbd604a529657a6e24edfe563ec553c881a'}} on vehicle run function animated_java:mushling/root/zzz/check_rig_hash
scoreboard players set @s aj.is_rig_loaded 1