# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.dirt_golem.root] run return 0
execute on passengers if entity @s[tag=aj.dirt_golem.data] unless data entity @s {data:{rigHash: '71038a85efe1396e054729a49dc4325705940a61a088668b3b1012a2ef410aff'}} on vehicle run function animated_java:dirt_golem/root/zzz/check_rig_hash
scoreboard players set @s aj.is_rig_loaded 1