# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.penguin.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'penguin', 'function_path': 'animated_java:penguin/variants/default_hurt/apply'}
execute on passengers if entity @s[tag=aj.penguin.bone.tail] run function animated_java:penguin/variants/default_hurt/zzz/0
execute on passengers if entity @s[tag=aj.penguin.bone.left_wing] run function animated_java:penguin/variants/default_hurt/zzz/1
execute on passengers if entity @s[tag=aj.penguin.bone.right_wing] run function animated_java:penguin/variants/default_hurt/zzz/2
execute on passengers if entity @s[tag=aj.penguin.bone.left_foot] run function animated_java:penguin/variants/default_hurt/zzz/3
execute on passengers if entity @s[tag=aj.penguin.bone.right_foot] run function animated_java:penguin/variants/default_hurt/zzz/4
execute on passengers if entity @s[tag=aj.penguin.bone.head] run function animated_java:penguin/variants/default_hurt/zzz/5
execute on passengers if entity @s[tag=aj.penguin.bone.body] run function animated_java:penguin/variants/default_hurt/zzz/6