# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
tag @s remove aj.mushling.animation.idle.playing
tag @s remove aj.mushling.animation.walk.playing
tag @s remove aj.mushling.animation.dig.playing