# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.snail.root] run return 0
execute on passengers if entity @s[tag=aj.snail.data] unless data entity @s {data:{rigHash: '7691f39e06af8600857915cd3ae2f9922402c7e2033a3fdbddc1d4b6c0ef6b9f'}} on vehicle run function animated_java:snail/root/zzz/check_rig_hash
scoreboard players set @s aj.is_rig_loaded 1