# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.snail.root] run return 0
execute if entity @s[tag=aj.snail.animation.idle.playing] run function animated_java:snail/animations/idle/zzz/on_tick
execute if entity @s[tag=aj.snail.animation.walk.playing] run function animated_java:snail/animations/walk/zzz/on_tick
execute if entity @s[tag=aj.snail.animation.hide.playing] run function animated_java:snail/animations/hide/zzz/on_tick
execute if entity @s[tag=aj.snail.animation.exit_hide.playing] run function animated_java:snail/animations/exit_hide/zzz/on_tick
#execute at @s on passengers run rotate @s ~ ~