# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.blueprint.root] run return 0
execute on passengers if entity @s[tag=aj.blueprint.data] unless data entity @s {data:{rigHash: '60762ebb65ed67bfe1567c0ebed39c5f59b41a5dcbd786c6752b471b7c3325a4'}} on vehicle run function animated_java:blueprint/root/zzz/0
scoreboard players set @s aj.is_rig_loaded 1