# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(block_display_block_display3) {transformation: [-0.4f,0f,0f,0.2f,0f,0.2828f,-0.2828f,-0.175f,0f,-0.2828f,-0.2828f,-0.2625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body) {transformation: [-1f,0f,0f,0f,0f,1f,0f,-0.625f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display_block_display) {transformation: [-0.3f,0f,0f,0.15f,0f,0.3f,0f,0f,0f,0f,-0.3f,0.3063f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display_block_display1) {transformation: [-0.15f,0f,0f,0.075f,0f,0.15f,0f,0f,0f,0f,-0.15f,0.4f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display_block_display2) {transformation: [-0.15f,0f,0f,0.075f,0f,0.15f,0f,0f,0f,0f,-0.15f,0.0563f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_upper) {transformation: [-1f,0f,0f,0f,0f,1f,0f,-0.625f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_lower) {transformation: [-1f,0f,0f,0f,0f,1f,0f,-0.625f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_front_left) {transformation: [-1f,0f,0f,0f,0f,1f,0f,-0.625f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_back_left) {transformation: [-1f,0f,0f,0f,0f,1f,0f,-0.625f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_front_right) {transformation: [-1f,0f,0f,0f,0f,1f,0f,-0.625f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_back_right) {transformation: [-1f,0f,0f,0f,0f,1f,0f,-0.625f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}