# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=minecraft:item_display,tag=aj.pufftail.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'pufftail', 'function_path': 'animated_java:pufftail/variants/default/apply'}
execute on passengers if entity @s[tag=aj.pufftail.bone.top_fin_3] run function animated_java:pufftail/variants/default/zzz/apply_to_bone_top_fin_3
execute on passengers if entity @s[tag=aj.pufftail.bone.top_fin_2] run function animated_java:pufftail/variants/default/zzz/apply_to_bone_top_fin_2
execute on passengers if entity @s[tag=aj.pufftail.bone.top_fin_1] run function animated_java:pufftail/variants/default/zzz/apply_to_bone_top_fin_1
execute on passengers if entity @s[tag=aj.pufftail.bone.body_front] run function animated_java:pufftail/variants/default/zzz/apply_to_bone_body_front
execute on passengers if entity @s[tag=aj.pufftail.bone.top_fin_4] run function animated_java:pufftail/variants/default/zzz/apply_to_bone_top_fin_4
execute on passengers if entity @s[tag=aj.pufftail.bone.top_fin_5] run function animated_java:pufftail/variants/default/zzz/apply_to_bone_top_fin_5
execute on passengers if entity @s[tag=aj.pufftail.bone.body_middle] run function animated_java:pufftail/variants/default/zzz/apply_to_bone_body_middle
execute on passengers if entity @s[tag=aj.pufftail.bone.top_fin_6] run function animated_java:pufftail/variants/default/zzz/apply_to_bone_top_fin_6
execute on passengers if entity @s[tag=aj.pufftail.bone.body_tail] run function animated_java:pufftail/variants/default/zzz/apply_to_bone_body_tail
execute on passengers if entity @s[tag=aj.pufftail.bone.back_right] run function animated_java:pufftail/variants/default/zzz/apply_to_bone_back_right
execute on passengers if entity @s[tag=aj.pufftail.bone.front_right] run function animated_java:pufftail/variants/default/zzz/apply_to_bone_front_right
execute on passengers if entity @s[tag=aj.pufftail.bone.front_left] run function animated_java:pufftail/variants/default/zzz/apply_to_bone_front_left
execute on passengers if entity @s[tag=aj.pufftail.bone.back_left] run function animated_java:pufftail/variants/default/zzz/apply_to_bone_back_left
return 1