# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.glare.root] run return 0
execute if entity @s[tag=aj.glare.animation.idle.playing] at @s if entity @e[type=player,distance=..32] run function animated_java:glare/animations/idle/zzz/on_tick
execute if entity @s[tag=aj.glare.animation.walk.playing] at @s if entity @e[type=player,distance=..32] run function animated_java:glare/animations/walk/zzz/on_tick
#execute at @s on passengers run rotate @s ~ ~