# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.treasure_chest.root] run return 0
execute on passengers if entity @s[tag=aj.treasure_chest.data] unless data entity @s {data:{rigHash: '0c55e7e06fa4be684e4e9f4fd819d398d0812106e870244b4631dd4815efa4e2'}} on vehicle run function animated_java:treasure_chest/root/zzz/check_rig_hash
scoreboard players set @s aj.is_rig_loaded 1