# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers if entity @s[tag=aj.hedgehog.bone.leg_left_front] run function animated_java:hedgehog/variants/brown_hurt/zzz/apply_to_bone_leg_left_front
execute on passengers if entity @s[tag=aj.hedgehog.bone.leg_right_back] run function animated_java:hedgehog/variants/brown_hurt/zzz/apply_to_bone_leg_right_back
execute on passengers if entity @s[tag=aj.hedgehog.bone.leg_right_front] run function animated_java:hedgehog/variants/brown_hurt/zzz/apply_to_bone_leg_right_front
execute on passengers if entity @s[tag=aj.hedgehog.bone.leg_left_back] run function animated_java:hedgehog/variants/brown_hurt/zzz/apply_to_bone_leg_left_back
execute on passengers if entity @s[tag=aj.hedgehog.bone.head] run function animated_java:hedgehog/variants/brown_hurt/zzz/apply_to_bone_head
execute on passengers if entity @s[tag=aj.hedgehog.bone.top] run function animated_java:hedgehog/variants/brown_hurt/zzz/apply_to_bone_top
execute on passengers if entity @s[tag=aj.hedgehog.bone.left] run function animated_java:hedgehog/variants/brown_hurt/zzz/apply_to_bone_left
execute on passengers if entity @s[tag=aj.hedgehog.bone.right] run function animated_java:hedgehog/variants/brown_hurt/zzz/apply_to_bone_right
execute on passengers if entity @s[tag=aj.hedgehog.bone.body] run function animated_java:hedgehog/variants/brown_hurt/zzz/apply_to_bone_body
execute on passengers if entity @s[tag=aj.hedgehog.bone.top1] run function animated_java:hedgehog/variants/brown_hurt/zzz/apply_to_bone_top1
execute on passengers if entity @s[tag=aj.hedgehog.bone.left1] run function animated_java:hedgehog/variants/brown_hurt/zzz/apply_to_bone_left1
execute on passengers if entity @s[tag=aj.hedgehog.bone.right1] run function animated_java:hedgehog/variants/brown_hurt/zzz/apply_to_bone_right1
execute on passengers if entity @s[tag=aj.hedgehog.bone.front] run function animated_java:hedgehog/variants/brown_hurt/zzz/apply_to_bone_front
execute on passengers if entity @s[tag=aj.hedgehog.bone.back] run function animated_java:hedgehog/variants/brown_hurt/zzz/apply_to_bone_back
execute on passengers if entity @s[tag=aj.hedgehog.bone.ball] run function animated_java:hedgehog/variants/brown_hurt/zzz/apply_to_bone_ball
return 1