# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.tuff_golem.root] run return 0
execute on passengers if entity @s[tag=aj.tuff_golem.data] unless data entity @s {data:{rigHash: '83b8cdd0d4dbd7905df2802d910b910b1259a29b4eb21c99a3e802884b9f77d3'}} on vehicle run function animated_java:tuff_golem/root/zzz/0
scoreboard players set @s aj.is_rig_loaded 1