# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.mushling.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'mushling', 'function_path': 'animated_java:mushling/variants/default/apply'}
execute on passengers if entity @s[tag=aj.mushling.bone.leg_right] run function animated_java:mushling/variants/default/zzz/0
execute on passengers if entity @s[tag=aj.mushling.bone.leg_left] run function animated_java:mushling/variants/default/zzz/1
execute on passengers if entity @s[tag=aj.mushling.bone.hat] run function animated_java:mushling/variants/default/zzz/2
execute on passengers if entity @s[tag=aj.mushling.bone.body] run function animated_java:mushling/variants/default/zzz/3