# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_head) {transformation: [-1f,0f,0f,0f,0f,1f,0f,-1.4781f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_mid) {transformation: [-1f,0f,0f,0f,0f,1f,0f,-1.4781f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_lower) {transformation: [-1f,0f,0f,0f,0f,1f,0f,-1.4021f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}