# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_body) {transformation: [-1f,0f,0f,0f,0f,1f,0f,-0.1875f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_head) {transformation: [-1f,0f,0f,0f,0f,1f,0f,-0.1875f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_1) {transformation: [-1f,0f,0f,0f,0f,1f,0f,-0.1875f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_2) {transformation: [-1f,0f,0f,0f,0f,1f,0f,-0.1875f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_3) {transformation: [-1f,0f,0f,0f,0f,1f,0f,-0.1875f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_4) {transformation: [-1f,0f,0f,0f,0f,1f,0f,-0.1875f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_back_left_foot) {transformation: [-1f,0f,0f,0f,0f,1f,0f,-0.1875f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_back_right_foot) {transformation: [-1f,0f,0f,0f,0f,1f,0f,-0.1875f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_front_right_foot) {transformation: [-1f,0f,0f,0f,0f,1f,0f,-0.1875f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_front_left_foot) {transformation: [-1f,0f,0f,0f,0f,1f,0f,-0.1875f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(item_display_item_display) {transformation: [0f,0f,0f,0f,0f,0f,0f,-0.125f,0f,0f,0f,0.0625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}