# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers if entity @s[tag=aj.rat.bone.body] run function animated_java:rat/variants/black_hurt/zzz/apply_to_bone_body
execute on passengers if entity @s[tag=aj.rat.bone.head] run function animated_java:rat/variants/black_hurt/zzz/apply_to_bone_head
execute on passengers if entity @s[tag=aj.rat.bone.1] run function animated_java:rat/variants/black_hurt/zzz/apply_to_bone_1
execute on passengers if entity @s[tag=aj.rat.bone.2] run function animated_java:rat/variants/black_hurt/zzz/apply_to_bone_2
execute on passengers if entity @s[tag=aj.rat.bone.3] run function animated_java:rat/variants/black_hurt/zzz/apply_to_bone_3
execute on passengers if entity @s[tag=aj.rat.bone.4] run function animated_java:rat/variants/black_hurt/zzz/apply_to_bone_4
execute on passengers if entity @s[tag=aj.rat.bone.back_left_foot] run function animated_java:rat/variants/black_hurt/zzz/apply_to_bone_back_left_foot
execute on passengers if entity @s[tag=aj.rat.bone.back_right_foot] run function animated_java:rat/variants/black_hurt/zzz/apply_to_bone_back_right_foot
execute on passengers if entity @s[tag=aj.rat.bone.front_right_foot] run function animated_java:rat/variants/black_hurt/zzz/apply_to_bone_front_right_foot
execute on passengers if entity @s[tag=aj.rat.bone.front_left_foot] run function animated_java:rat/variants/black_hurt/zzz/apply_to_bone_front_left_foot
return 1