# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers if entity @s[tag=aj.rat.bone.body] run data merge entity @s {transformation: [-1f,0f,0f,0f,0f,1f,0f,-0.1875f,0f,0f,-1f,0f,0f,0f,0f,1f], start_interpolation: 0}
execute on passengers if entity @s[tag=aj.rat.bone.head] run data merge entity @s {transformation: [-1f,0f,0f,0f,0f,1f,0f,-0.1875f,0f,0f,-1f,0f,0f,0f,0f,1f], start_interpolation: 0}
execute on passengers if entity @s[tag=aj.rat.bone.1] run data merge entity @s {transformation: [-1f,0f,0f,0f,0f,1f,0f,-0.1875f,0f,0f,-1f,0f,0f,0f,0f,1f], start_interpolation: 0}
execute on passengers if entity @s[tag=aj.rat.bone.2] run data merge entity @s {transformation: [-1f,0f,0f,0f,0f,1f,0f,-0.1875f,0f,0f,-1f,0f,0f,0f,0f,1f], start_interpolation: 0}
execute on passengers if entity @s[tag=aj.rat.bone.3] run data merge entity @s {transformation: [-1f,0f,0f,0f,0f,1f,0f,-0.1875f,0f,0f,-1f,0f,0f,0f,0f,1f], start_interpolation: 0}
execute on passengers if entity @s[tag=aj.rat.bone.4] run data merge entity @s {transformation: [-1f,0f,0f,0f,0f,1f,0f,-0.1875f,0f,0f,-1f,0f,0f,0f,0f,1f], start_interpolation: 0}
execute on passengers if entity @s[tag=aj.rat.bone.back_left_foot] run data merge entity @s {transformation: [-1f,0f,0f,0f,0f,1f,0f,-0.1875f,0f,0f,-1f,0f,0f,0f,0f,1f], start_interpolation: 0}
execute on passengers if entity @s[tag=aj.rat.bone.back_right_foot] run data merge entity @s {transformation: [-1f,0f,0f,0f,0f,1f,0f,-0.1875f,0f,0f,-1f,0f,0f,0f,0f,1f], start_interpolation: 0}
execute on passengers if entity @s[tag=aj.rat.bone.front_right_foot] run data merge entity @s {transformation: [-1f,0f,0f,0f,0f,1f,0f,-0.1875f,0f,0f,-1f,0f,0f,0f,0f,1f], start_interpolation: 0}
execute on passengers if entity @s[tag=aj.rat.bone.front_left_foot] run data merge entity @s {transformation: [-1f,0f,0f,0f,0f,1f,0f,-0.1875f,0f,0f,-1f,0f,0f,0f,0f,1f], start_interpolation: 0}
execute on passengers if entity @s[tag=aj.rat.bone.item_display] run data merge entity @s {transformation: [0f,0f,0f,0f,0f,0f,0f,-0.125f,0f,0f,0f,0.0625f,0f,0f,0f,1f], start_interpolation: 0}