# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.tuff_golem.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'tuff_golem', 'function_path': 'animated_java:tuff_golem/variants/light_gray/apply'}
execute on passengers if entity @s[tag=aj.tuff_golem.bone.head] run function animated_java:tuff_golem/variants/light_gray/zzz/0
execute on passengers if entity @s[tag=aj.tuff_golem.bone.body] run function animated_java:tuff_golem/variants/light_gray/zzz/1
execute on passengers if entity @s[tag=aj.tuff_golem.bone.clothing] run function animated_java:tuff_golem/variants/light_gray/zzz/2
execute on passengers if entity @s[tag=aj.tuff_golem.bone.left_leg] run function animated_java:tuff_golem/variants/light_gray/zzz/3
execute on passengers if entity @s[tag=aj.tuff_golem.bone.nose] run function animated_java:tuff_golem/variants/light_gray/zzz/4
execute on passengers if entity @s[tag=aj.tuff_golem.bone.right_leg] run function animated_java:tuff_golem/variants/light_gray/zzz/5
execute on passengers if entity @s[tag=aj.tuff_golem.bone.left_arm] run function animated_java:tuff_golem/variants/light_gray/zzz/6
execute on passengers if entity @s[tag=aj.tuff_golem.bone.right_arm] run function animated_java:tuff_golem/variants/light_gray/zzz/7
execute on passengers if entity @s[tag=aj.tuff_golem.bone.display] run function animated_java:tuff_golem/variants/light_gray/zzz/8