# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.mushling.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'mushling', 'function_path': 'animated_java:mushling/animations/dig/play'}
tag @s add aj.mushling.animation.dig.playing
scoreboard players set @s aj.dig.frame 0
tag @s add aj.transforms_only
execute at @s run function animated_java:mushling/animations/dig/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only