# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.copper_golem.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'copper_golem', 'function_path': 'animated_java:copper_golem/animations/button_press/next_frame'}
execute if score @s aj.button_press.frame matches 21.. run scoreboard players set @s aj.button_press.frame 1
execute store result storage aj:temp frame int 1 run scoreboard players get @s aj.button_press.frame
execute at @s run function animated_java:copper_golem/animations/button_press/zzz/apply_frame with storage aj:temp
scoreboard players add @s aj.button_press.frame 1