# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.penguin.root] run return 0
execute on passengers if entity @s[tag=aj.penguin.data] unless data entity @s {data:{rigHash: '05121cc333861c331fa16582732a9381ddb8159161f426c512727d38668a763b'}} on vehicle run function animated_java:penguin/root/zzz/0
scoreboard players set @s aj.is_rig_loaded 1