# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.penguin.root] run return 0
execute on passengers if entity @s[tag=aj.penguin.data] unless data entity @s {data:{rigHash: '246ca36fa0666dd8206fdba41b12415d09d0deeea6942c238fe1ac711a46e044'}} on vehicle run function animated_java:penguin/root/zzz/0
scoreboard players set @s aj.is_rig_loaded 1