# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.cruncher.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'cruncher', 'function_path': 'animated_java:cruncher/animations/pause_all'}
tag @s remove aj.cruncher.animation.idle.playing
tag @s remove aj.cruncher.animation.walk.playing
tag @s remove aj.cruncher.animation.fall.playing
tag @s remove aj.cruncher.animation.eat.playing