# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.bloomer.root] run return 0
execute on passengers if entity @s[tag=aj.bloomer.data] unless data entity @s {data:{rigHash: '5c4cf87101152bbbe3703c805a8c741e512522a0929573992bd0c41a03a1bbe2'}} on vehicle run function animated_java:bloomer/root/zzz/check_rig_hash
scoreboard players set @s aj.is_rig_loaded 1