# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.bloomer.root] run return 0
execute if entity @s[tag=aj.bloomer.animation.idle.playing] at @s if entity @e[type=player,distance=..32] run function animated_java:bloomer/animations/idle/zzz/on_tick
execute if entity @s[tag=aj.bloomer.animation.walk.playing] at @s if entity @e[type=player,distance=..32] run function animated_java:bloomer/animations/walk/zzz/on_tick
execute if entity @s[tag=aj.bloomer.animation.explode.playing] at @s if entity @e[type=player,distance=..32] run function animated_java:bloomer/animations/explode/zzz/on_tick