# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.nautilus_crab.root] run return 0
execute if entity @s[tag=aj.nautilus_crab.animation.idle.playing] run function animated_java:nautilus_crab/animations/idle/zzz/on_tick
execute if entity @s[tag=aj.nautilus_crab.animation.walk.playing] run function animated_java:nautilus_crab/animations/walk/zzz/on_tick
execute if entity @s[tag=aj.nautilus_crab.animation.dig.playing] run function animated_java:nautilus_crab/animations/dig/zzz/on_tick
#execute at @s on passengers run rotate @s ~ ~