# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data remove storage aj:temp args
$execute store result storage aj:temp args.frame int 1 run scoreboard players set @s aj.eat.frame $(frame)
execute at @s run function animated_java:rat/animations/eat/zzz/apply_frame with storage aj:temp args