# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_leg_left_front) {transformation: [-1f,0.0055f,0.0001f,0.1253f,0.0055f,0.9996f,0.0273f,-0.3132f,0f,0.0273f,-0.9996f,0.125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_leg_right_back) {transformation: [-1f,0.0055f,0.0001f,-0.1247f,0.0055f,0.9996f,0.0273f,-0.3118f,0f,0.0273f,-0.9996f,-0.1875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_leg_right_front) {transformation: [-1f,0.0055f,-0.0001f,-0.1247f,0.0055f,0.9996f,-0.0273f,-0.3118f,0f,-0.0273f,-0.9996f,0.125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_leg_left_back) {transformation: [-1f,0.0055f,-0.0001f,0.1253f,0.0055f,0.9996f,-0.0273f,-0.3132f,0f,-0.0273f,-0.9996f,-0.1875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_head) {transformation: [-1f,0.0055f,0f,0.0003f,0.0055f,1f,0f,-0.3125f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_top) {transformation: [-1f,0.0055f,0f,0f,0.0055f,1f,0f,-0.375f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_left) {transformation: [-1f,0.0055f,0f,0f,0.0055f,1f,0f,-0.375f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_right) {transformation: [-1f,0.0055f,0f,0f,0.0055f,1f,0f,-0.375f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_body) {transformation: [-1f,0.0055f,0f,0f,0.0055f,1f,0f,-0.375f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}