# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.data_data set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.hedgehog.node.leg_left_front] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_leg_left_front set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.hedgehog.node.leg_right_back] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_leg_right_back set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.hedgehog.node.leg_right_front] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_leg_right_front set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.hedgehog.node.leg_left_back] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_leg_left_back set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.hedgehog.node.head] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_head set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.hedgehog.node.top] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_top set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.hedgehog.node.left] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_left set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.hedgehog.node.right] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_right set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.hedgehog.node.body] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_body set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.hedgehog.node.top1] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_top1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.hedgehog.node.left1] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_left1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.hedgehog.node.right1] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_right1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.hedgehog.node.front] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_front set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.hedgehog.node.back] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_back set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.hedgehog.node.ball] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_ball set from storage aj:uuid main.out