# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=minecraft:item_display,tag=aj.vulture.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'vulture', 'function_path': 'animated_java:vulture/variants/default_hurt/apply'}
execute on passengers if entity @s[tag=aj.vulture.bone.body2] run function animated_java:vulture/variants/default_hurt/zzz/apply_to_bone_body2
execute on passengers if entity @s[tag=aj.vulture.bone.body3] run function animated_java:vulture/variants/default_hurt/zzz/apply_to_bone_body3
execute on passengers if entity @s[tag=aj.vulture.bone.head2] run function animated_java:vulture/variants/default_hurt/zzz/apply_to_bone_head2
execute on passengers if entity @s[tag=aj.vulture.bone.body] run function animated_java:vulture/variants/default_hurt/zzz/apply_to_bone_body
execute on passengers if entity @s[tag=aj.vulture.bone.left_tip] run function animated_java:vulture/variants/default_hurt/zzz/apply_to_bone_left_tip
execute on passengers if entity @s[tag=aj.vulture.bone.left_wing] run function animated_java:vulture/variants/default_hurt/zzz/apply_to_bone_left_wing
execute on passengers if entity @s[tag=aj.vulture.bone.right_tip] run function animated_java:vulture/variants/default_hurt/zzz/apply_to_bone_right_tip
execute on passengers if entity @s[tag=aj.vulture.bone.right_wing] run function animated_java:vulture/variants/default_hurt/zzz/apply_to_bone_right_wing
execute on passengers if entity @s[tag=aj.vulture.bone.tail] run function animated_java:vulture/variants/default_hurt/zzz/apply_to_bone_tail
execute on passengers if entity @s[tag=aj.vulture.bone.vulture] run function animated_java:vulture/variants/default_hurt/zzz/apply_to_bone_vulture
return 1