# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.dirt_golem.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'dirt_golem', 'function_path': 'animated_java:dirt_golem/variants/default_hurt/apply'}
execute on passengers if entity @s[tag=aj.dirt_golem.bone.body] run function animated_java:dirt_golem/variants/default_hurt/zzz/0
execute on passengers if entity @s[tag=aj.dirt_golem.bone.left_leg] run function animated_java:dirt_golem/variants/default_hurt/zzz/1
execute on passengers if entity @s[tag=aj.dirt_golem.bone.right_leg] run function animated_java:dirt_golem/variants/default_hurt/zzz/2
execute on passengers if entity @s[tag=aj.dirt_golem.bone.left_arm] run function animated_java:dirt_golem/variants/default_hurt/zzz/3
execute on passengers if entity @s[tag=aj.dirt_golem.bone.right_arm] run function animated_java:dirt_golem/variants/default_hurt/zzz/4
execute on passengers if entity @s[tag=aj.dirt_golem.bone.hat] run function animated_java:dirt_golem/variants/default_hurt/zzz/5