# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_top_fin_3) {transformation: [-1.6667f,0f,0f,0f,0f,1.6667f,0f,-2.5f,0f,0f,-1.6667f,-0.3125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_top_fin_2) {transformation: [-1.6667f,0f,0f,0f,0f,1.6667f,0f,-2.5f,0f,0f,-1.6667f,-0.3125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_top_fin_1) {transformation: [-1.525f,0f,0f,0f,0f,1.525f,0f,-2.5f,0f,0f,-1.525f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body_front) {transformation: [-1.5f,0f,0f,0f,0f,1.5f,0f,-2.5f,0f,0f,-1.5f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_top_fin_4) {transformation: [-1.625f,0f,0f,0f,0f,1.625f,0f,-2.5f,0f,0f,-1.625f,-0.3125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_top_fin_5) {transformation: [-1.5833f,0f,0f,0f,0f,1.5833f,0f,-2.5f,0f,0f,-1.5833f,-0.3125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body_middle) {transformation: [-1.2083f,0f,0f,0f,0f,1.2083f,0f,-2.5f,0f,0f,-1.2083f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_top_fin_6) {transformation: [-1.5667f,0f,0f,0f,0f,1.5667f,0f,-2.5f,0f,0f,-1.5667f,-0.3125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body_tail) {transformation: [-1.7917f,0f,0f,0f,0f,1.7917f,0f,-2.5f,0f,0f,-1.7917f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_back_right) {transformation: [-1.0833f,0f,0f,0f,0f,1.0833f,0f,-2.5f,0f,0f,-1.0833f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_front_right) {transformation: [-1.0417f,0f,0f,0f,0f,1.0417f,0f,-2.5f,0f,0f,-1.0417f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_front_left) {transformation: [-1.0417f,0f,0f,0f,0f,1.0417f,0f,-2.5f,0f,0f,-1.0417f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_back_left) {transformation: [-1.0833f,0f,0f,0f,0f,1.0833f,0f,-2.5f,0f,0f,-1.0833f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}