# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_top_fin_3) {transformation: [-1.6938f,0f,0f,0f,0f,1.6931f,0.048f,-2.4559f,0f,0.048f,-1.6931f,-0.3254f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_top_fin_2) {transformation: [-1.6938f,0f,0f,0f,0f,1.6931f,0.048f,-2.4559f,0f,0.048f,-1.6931f,-0.3254f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_top_fin_1) {transformation: [-1.5498f,0f,0f,0f,0f,1.5492f,0.0439f,-2.4794f,0f,0.0439f,-1.5492f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_body_front) {transformation: [-1.5244f,0f,0f,0f,0f,1.5238f,0.0432f,-2.4794f,0f,0.0432f,-1.5238f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_top_fin_4) {transformation: [-1.6514f,0f,0f,0f,0f,1.6514f,0f,-2.4794f,0f,0f,-1.6514f,-0.2844f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_top_fin_5) {transformation: [-1.6091f,0f,0f,0f,0f,1.6091f,0f,-2.4794f,0f,0f,-1.6091f,-0.2844f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_body_middle) {transformation: [-1.228f,0f,0f,0f,0f,1.228f,0f,-2.4794f,0f,0f,-1.228f,0.5413f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_top_fin_6) {transformation: [-1.5921f,0f,0f,0f,0f,1.5915f,-0.0451f,-2.4615f,0f,-0.0451f,-1.5915f,-0.2428f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_body_tail) {transformation: [-1.8208f,0f,0f,0f,0f,1.82f,-0.0516f,-2.4381f,0f,-0.0516f,-1.82f,0.5826f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_back_right) {transformation: [-1.0823f,-0.2018f,0f,0.1032f,-0.2018f,1.0823f,0f,-2.5826f,0f,0f,-1.1009f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_front_right) {transformation: [-1.0075f,-0.3249f,0f,0.1858f,-0.3249f,1.0075f,0f,-2.6858f,0f,0f,-1.0586f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_front_left) {transformation: [-1.0075f,0.3249f,0f,-0.2064f,0.3249f,1.0075f,0f,-2.6858f,0f,0f,-1.0586f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_back_left) {transformation: [-1.0823f,0.2018f,0f,-0.1032f,0.2018f,1.0823f,0f,-2.5867f,0f,0f,-1.1009f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}