# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_top_fin_3) {transformation: [-1.6979f,0f,0f,0f,0f,1.697f,0.0556f,-2.449f,0f,0.0556f,-1.697f,-0.3273f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_top_fin_2) {transformation: [-1.6979f,0f,0f,0f,0f,1.697f,0.0556f,-2.449f,0f,0.0556f,-1.697f,-0.3273f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_top_fin_1) {transformation: [-1.5536f,0f,0f,0f,0f,1.5528f,0.0508f,-2.4761f,0f,0.0508f,-1.5528f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_body_front) {transformation: [-1.5281f,0f,0f,0f,0f,1.5273f,0.05f,-2.4761f,0f,0.05f,-1.5273f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_top_fin_4) {transformation: [-1.6555f,0f,0f,0f,0f,1.6555f,0f,-2.4761f,0f,0f,-1.6555f,-0.28f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_top_fin_5) {transformation: [-1.613f,0f,0f,0f,0f,1.613f,0f,-2.4761f,0f,0f,-1.613f,-0.28f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_body_middle) {transformation: [-1.231f,0f,0f,0f,0f,1.231f,0f,-2.4761f,0f,0f,-1.231f,0.5478f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_top_fin_6) {transformation: [-1.596f,0f,0f,0f,0f,1.5952f,-0.0522f,-2.4555f,0f,-0.0522f,-1.5952f,-0.2318f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_body_tail) {transformation: [-1.8253f,0f,0f,0f,0f,1.8243f,-0.0597f,-2.4284f,0f,-0.0597f,-1.8243f,0.5955f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_back_right) {transformation: [-1.0788f,-0.233f,0f,0.1194f,-0.233f,1.0788f,0f,-2.5955f,0f,0f,-1.1036f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_front_right) {transformation: [-0.9932f,-0.3738f,0f,0.2149f,-0.3738f,0.9932f,0f,-2.7149f,0f,0f,-1.0612f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_front_left) {transformation: [-0.9932f,0.3738f,0f,-0.2388f,0.3738f,0.9932f,0f,-2.7149f,0f,0f,-1.0612f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_back_left) {transformation: [-1.0788f,0.233f,0f,-0.1194f,0.233f,1.0788f,0f,-2.6003f,0f,0f,-1.1036f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}