# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_top_fin_3) {transformation: [-1.7021f,0f,0f,0f,0f,1.7009f,0.0631f,-2.4421f,0f,0.0631f,-1.7009f,-0.3292f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_top_fin_2) {transformation: [-1.7021f,0f,0f,0f,0f,1.7009f,0.0631f,-2.4421f,0f,0.0631f,-1.7009f,-0.3292f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_top_fin_1) {transformation: [-1.5574f,0f,0f,0f,0f,1.5563f,0.0577f,-2.4729f,0f,0.0577f,-1.5563f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_body_front) {transformation: [-1.5319f,0f,0f,0f,0f,1.5308f,0.0568f,-2.4729f,0f,0.0568f,-1.5308f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_top_fin_4) {transformation: [-1.6595f,0f,0f,0f,0f,1.6595f,0f,-2.4729f,0f,0f,-1.6595f,-0.2755f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_top_fin_5) {transformation: [-1.617f,0f,0f,0f,0f,1.617f,0f,-2.4729f,0f,0f,-1.617f,-0.2755f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_body_middle) {transformation: [-1.234f,0f,0f,0f,0f,1.234f,0f,-2.4729f,0f,0f,-1.234f,0.5543f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_top_fin_6) {transformation: [-1.6f,0f,0f,0f,0f,1.5989f,-0.0593f,-2.4494f,0f,-0.0593f,-1.5989f,-0.2207f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_body_tail) {transformation: [-1.8297f,0f,0f,0f,0f,1.8285f,-0.0678f,-2.4186f,0f,-0.0678f,-1.8285f,0.6085f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_back_right) {transformation: [-1.0744f,-0.2641f,0f,0.1356f,-0.2641f,1.0744f,0f,-2.6085f,0f,0f,-1.1064f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_front_right) {transformation: [-0.9765f,-0.4221f,0f,0.2441f,-0.4221f,0.9765f,0f,-2.7441f,0f,0f,-1.0638f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_front_left) {transformation: [-0.9765f,0.4221f,0f,-0.2713f,0.4221f,0.9765f,0f,-2.7441f,0f,0f,-1.0638f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_back_left) {transformation: [-1.0744f,0.2641f,0f,-0.1356f,0.2641f,1.0744f,0f,-2.6139f,0f,0f,-1.1064f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}