# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_top_fin_3) {transformation: [-1.7042f,0f,0f,0f,0f,1.7029f,0.0669f,-2.4386f,0f,0.0669f,-1.7029f,-0.3301f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_top_fin_2) {transformation: [-1.7042f,0f,0f,0f,0f,1.7029f,0.0669f,-2.4386f,0f,0.0669f,-1.7029f,-0.3301f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_top_fin_1) {transformation: [-1.5593f,0f,0f,0f,0f,1.5581f,0.0612f,-2.4712f,0f,0.0612f,-1.5581f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_body_front) {transformation: [-1.5337f,0f,0f,0f,0f,1.5326f,0.0602f,-2.4712f,0f,0.0602f,-1.5326f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_top_fin_4) {transformation: [-1.6616f,0f,0f,0f,0f,1.6616f,0f,-2.4712f,0f,0f,-1.6616f,-0.2733f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_top_fin_5) {transformation: [-1.619f,0f,0f,0f,0f,1.619f,0f,-2.4712f,0f,0f,-1.619f,-0.2733f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_body_middle) {transformation: [-1.2355f,0f,0f,0f,0f,1.2355f,0f,-2.4712f,0f,0f,-1.2355f,0.5575f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_top_fin_6) {transformation: [-1.6019f,0f,0f,0f,0f,1.6007f,-0.0629f,-2.4463f,0f,-0.0629f,-1.6007f,-0.2151f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_body_tail) {transformation: [-1.832f,0f,0f,0f,0f,1.8306f,-0.0719f,-2.4137f,0f,-0.0719f,-1.8306f,0.615f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_back_right) {transformation: [-1.0718f,-0.2797f,0f,0.1438f,-0.2797f,1.0718f,0f,-2.615f,0f,0f,-1.1077f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_front_right) {transformation: [-0.9673f,-0.4459f,0f,0.2588f,-0.4459f,0.9673f,0f,-2.7588f,0f,0f,-1.0651f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_front_left) {transformation: [-0.9673f,0.4459f,0f,-0.2876f,0.4459f,0.9673f,0f,-2.7588f,0f,0f,-1.0651f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_back_left) {transformation: [-1.0718f,0.2797f,0f,-0.1438f,0.2797f,1.0718f,0f,-2.6208f,0f,0f,-1.1077f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}