# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_top_fin_3) {transformation: [-1.7062f,0f,0f,0f,0f,1.7048f,0.0707f,-2.4351f,0f,0.0707f,-1.7048f,-0.3311f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_top_fin_2) {transformation: [-1.7062f,0f,0f,0f,0f,1.7048f,0.0707f,-2.4351f,0f,0.0707f,-1.7048f,-0.3311f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_top_fin_1) {transformation: [-1.5612f,0f,0f,0f,0f,1.5599f,0.0647f,-2.4696f,0f,0.0647f,-1.5599f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body_front) {transformation: [-1.5356f,0f,0f,0f,0f,1.5343f,0.0636f,-2.4696f,0f,0.0636f,-1.5343f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_top_fin_4) {transformation: [-1.6636f,0f,0f,0f,0f,1.6636f,0f,-2.4696f,0f,0f,-1.6636f,-0.271f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_top_fin_5) {transformation: [-1.6209f,0f,0f,0f,0f,1.6209f,0f,-2.4696f,0f,0f,-1.6209f,-0.271f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body_middle) {transformation: [-1.237f,0f,0f,0f,0f,1.237f,0f,-2.4696f,0f,0f,-1.237f,0.5608f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_top_fin_6) {transformation: [-1.6039f,0f,0f,0f,0f,1.6025f,-0.0665f,-2.4433f,0f,-0.0665f,-1.6025f,-0.2095f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body_tail) {transformation: [-1.8342f,0f,0f,0f,0f,1.8326f,-0.076f,-2.4088f,0f,-0.076f,-1.8326f,0.6216f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_back_right) {transformation: [-1.069f,-0.2952f,0f,0.152f,-0.2952f,1.069f,0f,-2.6216f,0f,0f,-1.1091f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_front_right) {transformation: [-0.9575f,-0.4696f,0f,0.2735f,-0.4696f,0.9575f,0f,-2.7735f,0f,0f,-1.0664f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_front_left) {transformation: [-0.9575f,0.4696f,0f,-0.3039f,0.4696f,0.9575f,0f,-2.7735f,0f,0f,-1.0664f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_back_left) {transformation: [-1.069f,0.2952f,0f,-0.152f,0.2952f,1.069f,0f,-2.6276f,0f,0f,-1.1091f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}