# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_top_fin_3) {transformation: [-1.7167f,0f,0f,0f,0f,1.7143f,0.0898f,-2.4176f,0f,0.0898f,-1.7143f,-0.3357f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_top_fin_2) {transformation: [-1.7167f,0f,0f,0f,0f,1.7143f,0.0898f,-2.4176f,0f,0.0898f,-1.7143f,-0.3357f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_top_fin_1) {transformation: [-1.5707f,0f,0f,0f,0f,1.5686f,0.0822f,-2.4614f,0f,0.0822f,-1.5686f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_body_front) {transformation: [-1.545f,0f,0f,0f,0f,1.5429f,0.0809f,-2.4614f,0f,0.0809f,-1.5429f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_top_fin_4) {transformation: [-1.6737f,0f,0f,0f,0f,1.6738f,0f,-2.4614f,0f,0f,-1.6737f,-0.2596f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_top_fin_5) {transformation: [-1.6308f,0f,0f,0f,0f,1.6308f,0f,-2.4614f,0f,0f,-1.6308f,-0.2596f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_body_middle) {transformation: [-1.2446f,0f,0f,0f,0f,1.2446f,0f,-2.4614f,0f,0f,-1.2446f,0.5773f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_top_fin_6) {transformation: [-1.6137f,0f,0f,0f,0f,1.6115f,-0.0845f,-2.4279f,0f,-0.0845f,-1.6115f,-0.1812f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_body_tail) {transformation: [-1.8454f,0f,0f,0f,0f,1.8429f,-0.0966f,-2.3841f,0f,-0.0966f,-1.8429f,0.6545f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_back_right) {transformation: [-1.0518f,-0.3725f,0f,0.1931f,-0.3725f,1.0518f,0f,-2.6545f,0f,0f,-1.1158f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_front_right) {transformation: [-0.8998f,-0.5844f,0f,0.3476f,-0.5844f,0.8998f,0f,-2.8476f,0f,0f,-1.0729f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_front_left) {transformation: [-0.8998f,0.5844f,0f,-0.3863f,0.5844f,0.8998f,0f,-2.8476f,0f,0f,-1.0729f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_back_left) {transformation: [-1.0518f,0.3725f,0f,-0.1931f,0.3725f,1.0518f,0f,-2.6622f,0f,0f,-1.1158f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}