# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_top_fin_3) {transformation: [-1.7187f,0f,0f,0f,0f,1.7162f,0.0937f,-2.414f,0f,0.0937f,-1.7162f,-0.3366f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_top_fin_2) {transformation: [-1.7187f,0f,0f,0f,0f,1.7162f,0.0937f,-2.414f,0f,0.0937f,-1.7162f,-0.3366f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_top_fin_1) {transformation: [-1.5727f,0f,0f,0f,0f,1.5703f,0.0857f,-2.4597f,0f,0.0857f,-1.5703f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_body_front) {transformation: [-1.5469f,0f,0f,0f,0f,1.5446f,0.0843f,-2.4597f,0f,0.0843f,-1.5446f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_top_fin_4) {transformation: [-1.6758f,0f,0f,0f,0f,1.6758f,0f,-2.4597f,0f,0f,-1.6758f,-0.2573f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_top_fin_5) {transformation: [-1.6328f,0f,0f,0f,0f,1.6328f,0f,-2.4597f,0f,0f,-1.6328f,-0.2573f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_body_middle) {transformation: [-1.2461f,0f,0f,0f,0f,1.2461f,0f,-2.4597f,0f,0f,-1.2461f,0.5806f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_top_fin_6) {transformation: [-1.6156f,0f,0f,0f,0f,1.6132f,-0.0881f,-2.4248f,0f,-0.0881f,-1.6132f,-0.1755f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_body_tail) {transformation: [-1.8477f,0f,0f,0f,0f,1.8449f,-0.1007f,-2.3792f,0f,-0.1007f,-1.8449f,0.6611f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_back_right) {transformation: [-1.0477f,-0.3878f,0f,0.2014f,-0.3878f,1.0477f,0f,-2.6611f,0f,0f,-1.1172f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_front_right) {transformation: [-0.8866f,-0.6065f,0f,0.3625f,-0.6065f,0.8866f,0f,-2.8625f,0f,0f,-1.0742f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_front_left) {transformation: [-0.8866f,0.6065f,0f,-0.4028f,0.6065f,0.8866f,0f,-2.8625f,0f,0f,-1.0742f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_back_left) {transformation: [-1.0477f,0.3878f,0f,-0.2014f,0.3878f,1.0477f,0f,-2.6692f,0f,0f,-1.1172f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}