# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_top_fin_3) {transformation: [-1.7208f,0f,0f,0f,0f,1.7181f,0.0976f,-2.4105f,0f,0.0976f,-1.7181f,-0.3376f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_top_fin_2) {transformation: [-1.7208f,0f,0f,0f,0f,1.7181f,0.0976f,-2.4105f,0f,0.0976f,-1.7181f,-0.3376f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_top_fin_1) {transformation: [-1.5746f,0f,0f,0f,0f,1.572f,0.0893f,-2.4581f,0f,0.0893f,-1.572f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body_front) {transformation: [-1.5487f,0f,0f,0f,0f,1.5463f,0.0878f,-2.4581f,0f,0.0878f,-1.5463f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_top_fin_4) {transformation: [-1.6778f,0f,0f,0f,0f,1.6778f,0f,-2.4581f,0f,0f,-1.6778f,-0.255f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_top_fin_5) {transformation: [-1.6348f,0f,0f,0f,0f,1.6348f,0f,-2.4581f,0f,0f,-1.6348f,-0.255f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body_middle) {transformation: [-1.2476f,0f,0f,0f,0f,1.2476f,0f,-2.4581f,0f,0f,-1.2476f,0.5839f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_top_fin_6) {transformation: [-1.6176f,0f,0f,0f,0f,1.615f,-0.0917f,-2.4217f,0f,-0.0917f,-1.615f,-0.1698f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body_tail) {transformation: [-1.8499f,0f,0f,0f,0f,1.8469f,-0.1049f,-2.3742f,0f,-0.1049f,-1.8469f,0.6678f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_back_right) {transformation: [-1.0434f,-0.4031f,0f,0.2097f,-0.4031f,1.0434f,0f,-2.6678f,0f,0f,-1.1185f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_front_right) {transformation: [-0.8729f,-0.6284f,0f,0.3775f,-0.6284f,0.8729f,0f,-2.8775f,0f,0f,-1.0755f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_front_left) {transformation: [-0.8729f,0.6284f,0f,-0.4195f,0.6284f,0.8729f,0f,-2.8775f,0f,0f,-1.0755f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_back_left) {transformation: [-1.0434f,0.4031f,0f,-0.2097f,0.4031f,1.0434f,0f,-2.6762f,0f,0f,-1.1185f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}