# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_top_fin_3) {transformation: [-1.7229f,0f,0f,0f,0f,1.7199f,0.1014f,-2.4069f,0f,0.1014f,-1.7199f,-0.3385f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_top_fin_2) {transformation: [-1.7229f,0f,0f,0f,0f,1.7199f,0.1014f,-2.4069f,0f,0.1014f,-1.7199f,-0.3385f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_top_fin_1) {transformation: [-1.5765f,0f,0f,0f,0f,1.5737f,0.0928f,-2.4564f,0f,0.0928f,-1.5737f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body_front) {transformation: [-1.5506f,0f,0f,0f,0f,1.5479f,0.0913f,-2.4564f,0f,0.0913f,-1.5479f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_top_fin_4) {transformation: [-1.6798f,0f,0f,0f,0f,1.6798f,0f,-2.4564f,0f,0f,-1.6798f,-0.2527f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_top_fin_5) {transformation: [-1.6368f,0f,0f,0f,0f,1.6368f,0f,-2.4564f,0f,0f,-1.6368f,-0.2527f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body_middle) {transformation: [-1.2491f,0f,0f,0f,0f,1.2491f,0f,-2.4564f,0f,0f,-1.2491f,0.5872f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_top_fin_6) {transformation: [-1.6195f,0f,0f,0f,0f,1.6167f,-0.0953f,-2.4186f,0f,-0.0953f,-1.6167f,-0.164f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body_tail) {transformation: [-1.8521f,0f,0f,0f,0f,1.8489f,-0.109f,-2.3692f,0f,-0.109f,-1.8489f,0.6744f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_back_right) {transformation: [-1.0388f,-0.4184f,0f,0.2181f,-0.4184f,1.0388f,0f,-2.6744f,0f,0f,-1.1199f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_front_right) {transformation: [-0.8586f,-0.6499f,0f,0.3925f,-0.6499f,0.8586f,0f,-2.8925f,0f,0f,-1.0768f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_front_left) {transformation: [-0.8586f,0.6499f,0f,-0.4361f,0.6499f,0.8586f,0f,-2.8925f,0f,0f,-1.0768f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_back_left) {transformation: [-1.0388f,0.4184f,0f,-0.2181f,0.4184f,1.0388f,0f,-2.6832f,0f,0f,-1.1199f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}