# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_top_fin_3) {transformation: [-1.725f,0f,0f,0f,0f,1.7218f,0.1053f,-2.4034f,0f,0.1053f,-1.7218f,-0.3394f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_top_fin_2) {transformation: [-1.725f,0f,0f,0f,0f,1.7218f,0.1053f,-2.4034f,0f,0.1053f,-1.7218f,-0.3394f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_top_fin_1) {transformation: [-1.5784f,0f,0f,0f,0f,1.5754f,0.0964f,-2.4547f,0f,0.0964f,-1.5754f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body_front) {transformation: [-1.5525f,0f,0f,0f,0f,1.5496f,0.0948f,-2.4547f,0f,0.0948f,-1.5496f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_top_fin_4) {transformation: [-1.6819f,0f,0f,0f,0f,1.6819f,0f,-2.4547f,0f,0f,-1.6819f,-0.2504f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_top_fin_5) {transformation: [-1.6388f,0f,0f,0f,0f,1.6388f,0f,-2.4547f,0f,0f,-1.6388f,-0.2504f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body_middle) {transformation: [-1.2506f,0f,0f,0f,0f,1.2506f,0f,-2.4547f,0f,0f,-1.2506f,0.5906f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_top_fin_6) {transformation: [-1.6215f,0f,0f,0f,0f,1.6185f,-0.099f,-2.4155f,0f,-0.099f,-1.6185f,-0.1582f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body_tail) {transformation: [-1.8544f,0f,0f,0f,0f,1.8509f,-0.1132f,-2.3642f,0f,-0.1132f,-1.8509f,0.6811f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_back_right) {transformation: [-1.034f,-0.4336f,0f,0.2264f,-0.4336f,1.034f,0f,-2.6811f,0f,0f,-1.1212f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_front_right) {transformation: [-0.8437f,-0.6711f,0f,0.4075f,-0.6711f,0.8437f,0f,-2.9075f,0f,0f,-1.0781f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_front_left) {transformation: [-0.8437f,0.6711f,0f,-0.4528f,0.6711f,0.8437f,0f,-2.9075f,0f,0f,-1.0781f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_back_left) {transformation: [-1.034f,0.4336f,0f,-0.2264f,0.4336f,1.034f,0f,-2.6902f,0f,0f,-1.1212f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}