# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_top_fin_3) {transformation: [-1.7292f,0f,0f,0f,0f,1.7255f,0.1131f,-2.3962f,0f,0.1131f,-1.7255f,-0.3412f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_top_fin_2) {transformation: [-1.7292f,0f,0f,0f,0f,1.7255f,0.1131f,-2.3962f,0f,0.1131f,-1.7255f,-0.3412f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_top_fin_1) {transformation: [-1.5822f,0f,0f,0f,0f,1.5788f,0.1035f,-2.4514f,0f,0.1035f,-1.5788f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body_front) {transformation: [-1.5563f,0f,0f,0f,0f,1.5529f,0.1018f,-2.4514f,0f,0.1018f,-1.5529f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_top_fin_4) {transformation: [-1.6859f,0f,0f,0f,0f,1.6859f,0f,-2.4514f,0f,0f,-1.6859f,-0.2457f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_top_fin_5) {transformation: [-1.6427f,0f,0f,0f,0f,1.6427f,0f,-2.4514f,0f,0f,-1.6427f,-0.2457f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body_middle) {transformation: [-1.2536f,0f,0f,0f,0f,1.2536f,0f,-2.4514f,0f,0f,-1.2536f,0.5973f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_top_fin_6) {transformation: [-1.6254f,0f,0f,0f,0f,1.6219f,-0.1063f,-2.4092f,0f,-0.1063f,-1.6219f,-0.1466f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body_tail) {transformation: [-1.8589f,0f,0f,0f,0f,1.8549f,-0.1216f,-2.3541f,0f,-0.1216f,-1.8549f,0.6945f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_back_right) {transformation: [-1.0238f,-0.4639f,0f,0.2432f,-0.4639f,1.0238f,0f,-2.6945f,0f,0f,-1.124f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_front_right) {transformation: [-0.8125f,-0.7126f,0f,0.4377f,-0.7126f,0.8125f,0f,-2.9377f,0f,0f,-1.0807f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_front_left) {transformation: [-0.8125f,0.7126f,0f,-0.4863f,0.7126f,0.8125f,0f,-2.9377f,0f,0f,-1.0807f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_back_left) {transformation: [-1.0238f,0.4639f,0f,-0.2432f,0.4639f,1.0238f,0f,-2.7043f,0f,0f,-1.124f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}