# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_top_fin_3) {transformation: [-1.7312f,0f,0f,0f,0f,1.7273f,0.117f,-2.3926f,0f,0.117f,-1.7273f,-0.3421f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_top_fin_2) {transformation: [-1.7312f,0f,0f,0f,0f,1.7273f,0.117f,-2.3926f,0f,0.117f,-1.7273f,-0.3421f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_top_fin_1) {transformation: [-1.5841f,0f,0f,0f,0f,1.5805f,0.1071f,-2.4497f,0f,0.1071f,-1.5805f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body_front) {transformation: [-1.5581f,0f,0f,0f,0f,1.5546f,0.1053f,-2.4497f,0f,0.1053f,-1.5546f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_top_fin_4) {transformation: [-1.688f,0f,0f,0f,0f,1.688f,0f,-2.4497f,0f,0f,-1.688f,-0.2434f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_top_fin_5) {transformation: [-1.6447f,0f,0f,0f,0f,1.6447f,0f,-2.4497f,0f,0f,-1.6447f,-0.2434f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body_middle) {transformation: [-1.2552f,0f,0f,0f,0f,1.2552f,0f,-2.4497f,0f,0f,-1.2552f,0.6006f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_top_fin_6) {transformation: [-1.6274f,0f,0f,0f,0f,1.6237f,-0.11f,-2.4061f,0f,-0.11f,-1.6237f,-0.1408f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body_tail) {transformation: [-1.8611f,0f,0f,0f,0f,1.8568f,-0.1258f,-2.3491f,0f,-0.1258f,-1.8568f,0.7013f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_back_right) {transformation: [-1.0183f,-0.4789f,0f,0.2516f,-0.4789f,1.0183f,0f,-2.7013f,0f,0f,-1.1253f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_front_right) {transformation: [-0.7962f,-0.7327f,0f,0.4528f,-0.7327f,0.7962f,0f,-2.9528f,0f,0f,-1.082f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_front_left) {transformation: [-0.7962f,0.7327f,0f,-0.5031f,0.7327f,0.7962f,0f,-2.9528f,0f,0f,-1.082f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_back_left) {transformation: [-1.0183f,0.4789f,0f,-0.2516f,0.4789f,1.0183f,0f,-2.7113f,0f,0f,-1.1253f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}