# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_top_fin_3) {transformation: [-1.7333f,0f,0f,0f,0f,1.7291f,0.1209f,-2.3891f,0f,0.1209f,-1.7291f,-0.3429f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_top_fin_2) {transformation: [-1.7333f,0f,0f,0f,0f,1.7291f,0.1209f,-2.3891f,0f,0.1209f,-1.7291f,-0.3429f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_top_fin_1) {transformation: [-1.586f,0f,0f,0f,0f,1.5821f,0.1106f,-2.448f,0f,0.1106f,-1.5821f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_body_front) {transformation: [-1.56f,0f,0f,0f,0f,1.5562f,0.1088f,-2.448f,0f,0.1088f,-1.5562f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_top_fin_4) {transformation: [-1.69f,0f,0f,0f,0f,1.69f,0f,-2.448f,0f,0f,-1.69f,-0.241f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_top_fin_5) {transformation: [-1.6467f,0f,0f,0f,0f,1.6467f,0f,-2.448f,0f,0f,-1.6467f,-0.241f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_body_middle) {transformation: [-1.2567f,0f,0f,0f,0f,1.2567f,0f,-2.448f,0f,0f,-1.2567f,0.604f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_top_fin_6) {transformation: [-1.6293f,0f,0f,0f,0f,1.6254f,-0.1137f,-2.4029f,0f,-0.1137f,-1.6254f,-0.1349f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_body_tail) {transformation: [-1.8633f,0f,0f,0f,0f,1.8588f,-0.13f,-2.344f,0f,-0.13f,-1.8588f,0.708f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_back_right) {transformation: [-1.0126f,-0.4939f,0f,0.26f,-0.4939f,1.0126f,0f,-2.708f,0f,0f,-1.1267f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_front_right) {transformation: [-0.7793f,-0.7525f,0f,0.468f,-0.7525f,0.7793f,0f,-2.968f,0f,0f,-1.0833f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_front_left) {transformation: [-0.7793f,0.7525f,0f,-0.52f,0.7525f,0.7793f,0f,-2.968f,0f,0f,-1.0833f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_back_left) {transformation: [-1.0126f,0.4939f,0f,-0.26f,0.4939f,1.0126f,0f,-2.7184f,0f,0f,-1.1267f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}