# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_top_fin_3) {transformation: [-1.7354f,0f,0f,0f,0f,1.7309f,0.1248f,-2.3855f,0f,0.1248f,-1.7309f,-0.3438f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_top_fin_2) {transformation: [-1.7354f,0f,0f,0f,0f,1.7309f,0.1248f,-2.3855f,0f,0.1248f,-1.7309f,-0.3438f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_top_fin_1) {transformation: [-1.5879f,0f,0f,0f,0f,1.5838f,0.1142f,-2.4463f,0f,0.1142f,-1.5838f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_body_front) {transformation: [-1.5619f,0f,0f,0f,0f,1.5578f,0.1123f,-2.4463f,0f,0.1123f,-1.5578f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_top_fin_4) {transformation: [-1.692f,0f,0f,0f,0f,1.692f,0f,-2.4463f,0f,0f,-1.692f,-0.2386f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_top_fin_5) {transformation: [-1.6486f,0f,0f,0f,0f,1.6486f,0f,-2.4463f,0f,0f,-1.6486f,-0.2386f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_body_middle) {transformation: [-1.2582f,0f,0f,0f,0f,1.2582f,0f,-2.4463f,0f,0f,-1.2582f,0.6074f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_top_fin_6) {transformation: [-1.6313f,0f,0f,0f,0f,1.6271f,-0.1173f,-2.3998f,0f,-0.1173f,-1.6271f,-0.1291f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_body_tail) {transformation: [-1.8656f,0f,0f,0f,0f,1.8607f,-0.1342f,-2.3389f,0f,-0.1342f,-1.8607f,0.7148f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_back_right) {transformation: [-1.0067f,-0.5088f,0f,0.2684f,-0.5088f,1.0067f,0f,-2.7148f,0f,0f,-1.128f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_front_right) {transformation: [-0.7619f,-0.772f,0f,0.4832f,-0.772f,0.7619f,0f,-2.9832f,0f,0f,-1.0846f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_front_left) {transformation: [-0.7619f,0.772f,0f,-0.5369f,0.772f,0.7619f,0f,-2.9832f,0f,0f,-1.0846f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_back_left) {transformation: [-1.0067f,0.5088f,0f,-0.2684f,0.5088f,1.0067f,0f,-2.7255f,0f,0f,-1.128f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}