# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_top_fin_3) {transformation: [-1.7375f,0f,0f,0f,0f,1.7327f,0.1288f,-2.3818f,0f,0.1288f,-1.7327f,-0.3447f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_top_fin_2) {transformation: [-1.7375f,0f,0f,0f,0f,1.7327f,0.1288f,-2.3818f,0f,0.1288f,-1.7327f,-0.3447f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_top_fin_1) {transformation: [-1.5898f,0f,0f,0f,0f,1.5854f,0.1178f,-2.4446f,0f,0.1178f,-1.5854f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_body_front) {transformation: [-1.5637f,0f,0f,0f,0f,1.5594f,0.1159f,-2.4446f,0f,0.1159f,-1.5594f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_top_fin_4) {transformation: [-1.6941f,0f,0f,0f,0f,1.6941f,0f,-2.4446f,0f,0f,-1.6941f,-0.2363f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_top_fin_5) {transformation: [-1.6506f,0f,0f,0f,0f,1.6506f,0f,-2.4446f,0f,0f,-1.6506f,-0.2363f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_body_middle) {transformation: [-1.2597f,0f,0f,0f,0f,1.2597f,0f,-2.4446f,0f,0f,-1.2597f,0.6108f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_top_fin_6) {transformation: [-1.6332f,0f,0f,0f,0f,1.6288f,-0.121f,-2.3966f,0f,-0.121f,-1.6288f,-0.1232f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_body_tail) {transformation: [-1.8678f,0f,0f,0f,0f,1.8627f,-0.1384f,-2.3339f,0f,-0.1384f,-1.8627f,0.7215f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_back_right) {transformation: [-1.0006f,-0.5237f,0f,0.2769f,-0.5237f,1.0006f,0f,-2.7215f,0f,0f,-1.1294f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_front_right) {transformation: [-0.7441f,-0.791f,0f,0.4984f,-0.791f,0.7441f,0f,-2.9984f,0f,0f,-1.0859f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_front_left) {transformation: [-0.7441f,0.791f,0f,-0.5538f,0.791f,0.7441f,0f,-2.9984f,0f,0f,-1.0859f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_back_left) {transformation: [-1.0006f,0.5237f,0f,-0.2769f,0.5237f,1.0006f,0f,-2.7326f,0f,0f,-1.1294f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}