# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_top_fin_3) {transformation: [-1.7396f,0f,0f,0f,0f,1.7345f,0.1327f,-2.3782f,0f,0.1327f,-1.7345f,-0.3456f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_top_fin_2) {transformation: [-1.7396f,0f,0f,0f,0f,1.7345f,0.1327f,-2.3782f,0f,0.1327f,-1.7345f,-0.3456f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_top_fin_1) {transformation: [-1.5917f,0f,0f,0f,0f,1.5871f,0.1214f,-2.4429f,0f,0.1214f,-1.5871f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body_front) {transformation: [-1.5656f,0f,0f,0f,0f,1.5611f,0.1194f,-2.4429f,0f,0.1194f,-1.5611f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_top_fin_4) {transformation: [-1.6961f,0f,0f,0f,0f,1.6961f,0f,-2.4429f,0f,0f,-1.6961f,-0.2339f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_top_fin_5) {transformation: [-1.6526f,0f,0f,0f,0f,1.6526f,0f,-2.4429f,0f,0f,-1.6526f,-0.2339f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body_middle) {transformation: [-1.2612f,0f,0f,0f,0f,1.2612f,0f,-2.4429f,0f,0f,-1.2612f,0.6142f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_top_fin_6) {transformation: [-1.6352f,0f,0f,0f,0f,1.6304f,-0.1247f,-2.3935f,0f,-0.1247f,-1.6304f,-0.1173f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body_tail) {transformation: [-1.8701f,0f,0f,0f,0f,1.8646f,-0.1427f,-2.3288f,0f,-0.1427f,-1.8646f,0.7283f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_back_right) {transformation: [-0.9943f,-0.5385f,0f,0.2854f,-0.5385f,0.9943f,0f,-2.7283f,0f,0f,-1.1307f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_front_right) {transformation: [-0.7257f,-0.8096f,0f,0.5137f,-0.8096f,0.7257f,0f,-3.0137f,0f,0f,-1.0872f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_front_left) {transformation: [-0.7257f,0.8096f,0f,-0.5708f,0.8096f,0.7257f,0f,-3.0137f,0f,0f,-1.0872f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_back_left) {transformation: [-0.9943f,0.5385f,0f,-0.2854f,0.5385f,0.9943f,0f,-2.7397f,0f,0f,-1.1307f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}