# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_top_fin_3) {transformation: [-1.7417f,0f,0f,0f,0f,1.7363f,0.1366f,-2.3746f,0f,0.1366f,-1.7363f,-0.3464f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_top_fin_2) {transformation: [-1.7417f,0f,0f,0f,0f,1.7363f,0.1366f,-2.3746f,0f,0.1366f,-1.7363f,-0.3464f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_top_fin_1) {transformation: [-1.5936f,0f,0f,0f,0f,1.5887f,0.125f,-2.4412f,0f,0.125f,-1.5887f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_body_front) {transformation: [-1.5675f,0f,0f,0f,0f,1.5627f,0.123f,-2.4412f,0f,0.123f,-1.5627f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_top_fin_4) {transformation: [-1.6981f,0f,0f,0f,0f,1.6981f,0f,-2.4412f,0f,0f,-1.6981f,-0.2315f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_top_fin_5) {transformation: [-1.6546f,0f,0f,0f,0f,1.6546f,0f,-2.4412f,0f,0f,-1.6546f,-0.2315f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_body_middle) {transformation: [-1.2627f,0f,0f,0f,0f,1.2627f,0f,-2.4412f,0f,0f,-1.2627f,0.6176f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_top_fin_6) {transformation: [-1.6372f,0f,0f,0f,0f,1.6321f,-0.1285f,-2.3903f,0f,-0.1285f,-1.6321f,-0.1113f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_body_tail) {transformation: [-1.8723f,0f,0f,0f,0f,1.8665f,-0.1469f,-2.3237f,0f,-0.1469f,-1.8665f,0.7351f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_back_right) {transformation: [-0.9877f,-0.5532f,0f,0.2939f,-0.5532f,0.9877f,0f,-2.7351f,0f,0f,-1.1321f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_front_right) {transformation: [-0.707f,-0.8277f,0f,0.529f,-0.8277f,0.707f,0f,-3.029f,0f,0f,-1.0885f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_front_left) {transformation: [-0.707f,0.8277f,0f,-0.5878f,0.8277f,0.707f,0f,-3.029f,0f,0f,-1.0885f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_back_left) {transformation: [-0.9877f,0.5532f,0f,-0.2939f,0.5532f,0.9877f,0f,-2.7469f,0f,0f,-1.1321f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}