# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_top_fin_3) {transformation: [-1.7438f,0f,0f,0f,0f,1.7381f,0.1406f,-2.371f,0f,0.1406f,-1.7381f,-0.3473f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_top_fin_2) {transformation: [-1.7438f,0f,0f,0f,0f,1.7381f,0.1406f,-2.371f,0f,0.1406f,-1.7381f,-0.3473f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_top_fin_1) {transformation: [-1.5955f,0f,0f,0f,0f,1.5903f,0.1287f,-2.4395f,0f,0.1287f,-1.5903f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_body_front) {transformation: [-1.5694f,0f,0f,0f,0f,1.5643f,0.1265f,-2.4395f,0f,0.1265f,-1.5643f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_top_fin_4) {transformation: [-1.7002f,0f,0f,0f,0f,1.7002f,0f,-2.4395f,0f,0f,-1.7002f,-0.2291f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_top_fin_5) {transformation: [-1.6566f,0f,0f,0f,0f,1.6566f,0f,-2.4395f,0f,0f,-1.6566f,-0.2291f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_body_middle) {transformation: [-1.2642f,0f,0f,0f,0f,1.2642f,0f,-2.4395f,0f,0f,-1.2642f,0.621f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_top_fin_6) {transformation: [-1.6391f,0f,0f,0f,0f,1.6338f,-0.1322f,-2.3871f,0f,-0.1322f,-1.6338f,-0.1054f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_body_tail) {transformation: [-1.8745f,0f,0f,0f,0f,1.8684f,-0.1512f,-2.3185f,0f,-0.1512f,-1.8684f,0.7419f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_back_right) {transformation: [-0.981f,-0.5678f,0f,0.3024f,-0.5678f,0.981f,0f,-2.7419f,0f,0f,-1.1334f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_front_right) {transformation: [-0.6877f,-0.8455f,0f,0.5444f,-0.8455f,0.6877f,0f,-3.0444f,0f,0f,-1.0898f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_front_left) {transformation: [-0.6877f,0.8455f,0f,-0.6049f,0.8455f,0.6877f,0f,-3.0444f,0f,0f,-1.0898f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_back_left) {transformation: [-0.981f,0.5678f,0f,-0.3024f,0.5678f,0.981f,0f,-2.754f,0f,0f,-1.1334f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}