# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_top_fin_3) {transformation: [-1.75f,0f,0f,0f,0f,1.7433f,0.1525f,-2.36f,0f,0.1525f,-1.7433f,-0.3499f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_top_fin_2) {transformation: [-1.75f,0f,0f,0f,0f,1.7433f,0.1525f,-2.36f,0f,0.1525f,-1.7433f,-0.3499f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_top_fin_1) {transformation: [-1.6013f,0f,0f,0f,0f,1.5952f,0.1396f,-2.4344f,0f,0.1396f,-1.5952f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body_front) {transformation: [-1.575f,0f,0f,0f,0f,1.569f,0.1373f,-2.4344f,0f,0.1373f,-1.569f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_top_fin_4) {transformation: [-1.7062f,0f,0f,0f,0f,1.7063f,0f,-2.4344f,0f,0f,-1.7062f,-0.2219f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_top_fin_5) {transformation: [-1.6625f,0f,0f,0f,0f,1.6625f,0f,-2.4344f,0f,0f,-1.6625f,-0.2219f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body_middle) {transformation: [-1.2687f,0f,0f,0f,0f,1.2688f,0f,-2.4344f,0f,0f,-1.2687f,0.6313f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_top_fin_6) {transformation: [-1.645f,0f,0f,0f,0f,1.6387f,-0.1434f,-2.3775f,0f,-0.1434f,-1.6387f,-0.0874f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body_tail) {transformation: [-1.8812f,0f,0f,0f,0f,1.8741f,-0.164f,-2.3031f,0f,-0.164f,-1.8741f,0.7625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_back_right) {transformation: [-0.9594f,-0.6112f,0f,0.3281f,-0.6112f,0.9594f,0f,-2.7625f,0f,0f,-1.1375f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_front_right) {transformation: [-0.6273f,-0.8959f,0f,0.5906f,-0.8959f,0.6273f,0f,-3.0906f,0f,0f,-1.0938f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_front_left) {transformation: [-0.6273f,0.8959f,0f,-0.6563f,0.8959f,0.6273f,0f,-3.0906f,0f,0f,-1.0938f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_back_left) {transformation: [-0.9594f,0.6112f,0f,-0.3281f,0.6112f,0.9594f,0f,-2.7756f,0f,0f,-1.1375f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}