# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_top_fin_3) {transformation: [-1.7479f,0f,0f,0f,0f,1.7416f,0.1485f,-2.3637f,0f,0.1485f,-1.7416f,-0.349f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_top_fin_2) {transformation: [-1.7479f,0f,0f,0f,0f,1.7416f,0.1485f,-2.3637f,0f,0.1485f,-1.7416f,-0.349f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_top_fin_1) {transformation: [-1.5993f,0f,0f,0f,0f,1.5936f,0.1359f,-2.4361f,0f,0.1359f,-1.5936f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_body_front) {transformation: [-1.5731f,0f,0f,0f,0f,1.5674f,0.1337f,-2.4361f,0f,0.1337f,-1.5674f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_top_fin_4) {transformation: [-1.7042f,0f,0f,0f,0f,1.7042f,0f,-2.4361f,0f,0f,-1.7042f,-0.2243f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_top_fin_5) {transformation: [-1.6605f,0f,0f,0f,0f,1.6605f,0f,-2.4361f,0f,0f,-1.6605f,-0.2243f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_body_middle) {transformation: [-1.2672f,0f,0f,0f,0f,1.2672f,0f,-2.4361f,0f,0f,-1.2672f,0.6278f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_top_fin_6) {transformation: [-1.643f,0f,0f,0f,0f,1.6371f,-0.1396f,-2.3807f,0f,-0.1396f,-1.6371f,-0.0934f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_body_tail) {transformation: [-1.879f,0f,0f,0f,0f,1.8722f,-0.1597f,-2.3083f,0f,-0.1597f,-1.8722f,0.7556f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_back_right) {transformation: [-0.9668f,-0.5968f,0f,0.3195f,-0.5968f,0.9668f,0f,-2.7556f,0f,0f,-1.1361f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_front_right) {transformation: [-0.6479f,-0.8796f,0f,0.5752f,-0.8796f,0.6479f,0f,-3.0752f,0f,0f,-1.0924f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_front_left) {transformation: [-0.6479f,0.8796f,0f,-0.6391f,0.8796f,0.6479f,0f,-3.0752f,0f,0f,-1.0924f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_back_left) {transformation: [-0.9668f,0.5968f,0f,-0.3195f,0.5968f,0.9668f,0f,-2.7684f,0f,0f,-1.1361f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}