# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_top_fin_3) {transformation: [-1.7458f,0f,0f,0f,0f,1.7398f,0.1446f,-2.3673f,0f,0.1446f,-1.7398f,-0.3482f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_top_fin_2) {transformation: [-1.7458f,0f,0f,0f,0f,1.7398f,0.1446f,-2.3673f,0f,0.1446f,-1.7398f,-0.3482f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_top_fin_1) {transformation: [-1.5974f,0f,0f,0f,0f,1.592f,0.1323f,-2.4378f,0f,0.1323f,-1.592f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_body_front) {transformation: [-1.5712f,0f,0f,0f,0f,1.5659f,0.1301f,-2.4378f,0f,0.1301f,-1.5659f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_top_fin_4) {transformation: [-1.7022f,0f,0f,0f,0f,1.7022f,0f,-2.4378f,0f,0f,-1.7022f,-0.2267f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_top_fin_5) {transformation: [-1.6585f,0f,0f,0f,0f,1.6585f,0f,-2.4378f,0f,0f,-1.6585f,-0.2267f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_body_middle) {transformation: [-1.2657f,0f,0f,0f,0f,1.2657f,0f,-2.4378f,0f,0f,-1.2657f,0.6244f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_top_fin_6) {transformation: [-1.6411f,0f,0f,0f,0f,1.6354f,-0.1359f,-2.3839f,0f,-0.1359f,-1.6354f,-0.0994f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_body_tail) {transformation: [-1.8768f,0f,0f,0f,0f,1.8703f,-0.1554f,-2.3134f,0f,-0.1554f,-1.8703f,0.7488f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_back_right) {transformation: [-0.974f,-0.5823f,0f,0.311f,-0.5823f,0.974f,0f,-2.7488f,0f,0f,-1.1348f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_front_right) {transformation: [-0.668f,-0.8628f,0f,0.5598f,-0.8628f,0.668f,0f,-3.0598f,0f,0f,-1.0911f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_front_left) {transformation: [-0.668f,0.8628f,0f,-0.622f,0.8628f,0.668f,0f,-3.0598f,0f,0f,-1.0911f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_back_left) {transformation: [-0.974f,0.5823f,0f,-0.311f,0.5823f,0.974f,0f,-2.7612f,0f,0f,-1.1348f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}