# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_top_fin_3) {transformation: [-1.7271f,0f,0f,0f,0f,1.7236f,0.1092f,-2.3998f,0f,0.1092f,-1.7236f,-0.3403f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_top_fin_2) {transformation: [-1.7271f,0f,0f,0f,0f,1.7236f,0.1092f,-2.3998f,0f,0.1092f,-1.7236f,-0.3403f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_top_fin_1) {transformation: [-1.5803f,0f,0f,0f,0f,1.5771f,0.0999f,-2.453f,0f,0.0999f,-1.5771f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_body_front) {transformation: [-1.5544f,0f,0f,0f,0f,1.5513f,0.0983f,-2.453f,0f,0.0983f,-1.5513f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_top_fin_4) {transformation: [-1.6839f,0f,0f,0f,0f,1.6839f,0f,-2.453f,0f,0f,-1.6839f,-0.248f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_top_fin_5) {transformation: [-1.6407f,0f,0f,0f,0f,1.6407f,0f,-2.453f,0f,0f,-1.6407f,-0.248f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_body_middle) {transformation: [-1.2521f,0f,0f,0f,0f,1.2521f,0f,-2.453f,0f,0f,-1.2521f,0.5939f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_top_fin_6) {transformation: [-1.6235f,0f,0f,0f,0f,1.6202f,-0.1026f,-2.4124f,0f,-0.1026f,-1.6202f,-0.1524f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_body_tail) {transformation: [-1.8566f,0f,0f,0f,0f,1.8529f,-0.1174f,-2.3591f,0f,-0.1174f,-1.8529f,0.6878f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_back_right) {transformation: [-1.029f,-0.4488f,0f,0.2348f,-0.4488f,1.029f,0f,-2.6878f,0f,0f,-1.1226f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_front_right) {transformation: [-0.8284f,-0.692f,0f,0.4226f,-0.692f,0.8284f,0f,-2.9226f,0f,0f,-1.0794f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_front_left) {transformation: [-0.8284f,0.692f,0f,-0.4696f,0.692f,0.8284f,0f,-2.9226f,0f,0f,-1.0794f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_back_left) {transformation: [-1.029f,0.4488f,0f,-0.2348f,0.4488f,1.029f,0f,-2.6972f,0f,0f,-1.1226f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}