# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_top_fin_3) {transformation: [-1.7146f,0f,0f,0f,0f,1.7124f,0.086f,-2.4211f,0f,0.086f,-1.7124f,-0.3348f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_top_fin_2) {transformation: [-1.7146f,0f,0f,0f,0f,1.7124f,0.086f,-2.4211f,0f,0.086f,-1.7124f,-0.3348f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_top_fin_1) {transformation: [-1.5688f,0f,0f,0f,0f,1.5669f,0.0787f,-2.463f,0f,0.0787f,-1.5669f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body_front) {transformation: [-1.5431f,0f,0f,0f,0f,1.5412f,0.0774f,-2.463f,0f,0.0774f,-1.5412f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_top_fin_4) {transformation: [-1.6717f,0f,0f,0f,0f,1.6717f,0f,-2.463f,0f,0f,-1.6717f,-0.2619f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_top_fin_5) {transformation: [-1.6289f,0f,0f,0f,0f,1.6289f,0f,-2.463f,0f,0f,-1.6289f,-0.2619f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body_middle) {transformation: [-1.2431f,0f,0f,0f,0f,1.2431f,0f,-2.463f,0f,0f,-1.2431f,0.5739f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_top_fin_6) {transformation: [-1.6117f,0f,0f,0f,0f,1.6097f,-0.0808f,-2.431f,0f,-0.0808f,-1.6097f,-0.1869f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body_tail) {transformation: [-1.8432f,0f,0f,0f,0f,1.8409f,-0.0924f,-2.3891f,0f,-0.0924f,-1.8409f,0.6479f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_back_right) {transformation: [-1.0557f,-0.3571f,0f,0.1849f,-0.3571f,1.0557f,0f,-2.6479f,0f,0f,-1.1145f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_front_right) {transformation: [-0.9125f,-0.5619f,0f,0.3327f,-0.5619f,0.9125f,0f,-2.8327f,0f,0f,-1.0716f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_front_left) {transformation: [-0.9125f,0.5619f,0f,-0.3697f,0.5619f,0.9125f,0f,-2.8327f,0f,0f,-1.0716f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_back_left) {transformation: [-1.0557f,0.3571f,0f,-0.1849f,0.3571f,1.0557f,0f,-2.6553f,0f,0f,-1.1145f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}