# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_top_fin_3) {transformation: [-1.7125f,0f,0f,0f,0f,1.7105f,0.0822f,-2.4246f,0f,0.0822f,-1.7105f,-0.3339f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_top_fin_2) {transformation: [-1.7125f,0f,0f,0f,0f,1.7105f,0.0822f,-2.4246f,0f,0.0822f,-1.7105f,-0.3339f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_top_fin_1) {transformation: [-1.5669f,0f,0f,0f,0f,1.5651f,0.0752f,-2.4647f,0f,0.0752f,-1.5651f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_body_front) {transformation: [-1.5413f,0f,0f,0f,0f,1.5395f,0.0739f,-2.4647f,0f,0.0739f,-1.5395f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_top_fin_4) {transformation: [-1.6697f,0f,0f,0f,0f,1.6697f,0f,-2.4647f,0f,0f,-1.6697f,-0.2642f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_top_fin_5) {transformation: [-1.6269f,0f,0f,0f,0f,1.6269f,0f,-2.4647f,0f,0f,-1.6269f,-0.2642f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_body_middle) {transformation: [-1.2416f,0f,0f,0f,0f,1.2416f,0f,-2.4647f,0f,0f,-1.2416f,0.5706f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_top_fin_6) {transformation: [-1.6098f,0f,0f,0f,0f,1.6079f,-0.0772f,-2.4341f,0f,-0.0772f,-1.6079f,-0.1926f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_body_tail) {transformation: [-1.8409f,0f,0f,0f,0f,1.8388f,-0.0883f,-2.394f,0f,-0.0883f,-1.8388f,0.6413f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_back_right) {transformation: [-1.0594f,-0.3417f,0f,0.1766f,-0.3417f,1.0594f,0f,-2.6413f,0f,0f,-1.1131f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_front_right) {transformation: [-0.9246f,-0.5392f,0f,0.3179f,-0.5392f,0.9246f,0f,-2.8179f,0f,0f,-1.0703f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_front_left) {transformation: [-0.9246f,0.5392f,0f,-0.3532f,0.5392f,0.9246f,0f,-2.8179f,0f,0f,-1.0703f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_back_left) {transformation: [-1.0594f,0.3417f,0f,-0.1766f,0.3417f,1.0594f,0f,-2.6483f,0f,0f,-1.1131f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}