# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_top_fin_3) {transformation: [-1.7104f,0f,0f,0f,0f,1.7086f,0.0783f,-2.4281f,0f,0.0783f,-1.7086f,-0.333f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_top_fin_2) {transformation: [-1.7104f,0f,0f,0f,0f,1.7086f,0.0783f,-2.4281f,0f,0.0783f,-1.7086f,-0.333f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_top_fin_1) {transformation: [-1.565f,0f,0f,0f,0f,1.5634f,0.0717f,-2.4663f,0f,0.0717f,-1.5634f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body_front) {transformation: [-1.5394f,0f,0f,0f,0f,1.5378f,0.0705f,-2.4663f,0f,0.0705f,-1.5378f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_top_fin_4) {transformation: [-1.6677f,0f,0f,0f,0f,1.6677f,0f,-2.4663f,0f,0f,-1.6677f,-0.2665f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_top_fin_5) {transformation: [-1.6249f,0f,0f,0f,0f,1.6249f,0f,-2.4663f,0f,0f,-1.6249f,-0.2665f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body_middle) {transformation: [-1.2401f,0f,0f,0f,0f,1.2401f,0f,-2.4663f,0f,0f,-1.2401f,0.5673f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_top_fin_6) {transformation: [-1.6078f,0f,0f,0f,0f,1.6061f,-0.0736f,-2.4372f,0f,-0.0736f,-1.6061f,-0.1983f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body_tail) {transformation: [-1.8387f,0f,0f,0f,0f,1.8368f,-0.0842f,-2.399f,0f,-0.0842f,-1.8368f,0.6347f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_back_right) {transformation: [-1.0628f,-0.3262f,0f,0.1684f,-0.3262f,1.0628f,0f,-2.6347f,0f,0f,-1.1118f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_front_right) {transformation: [-0.9361f,-0.5162f,0f,0.3031f,-0.5162f,0.9361f,0f,-2.8031f,0f,0f,-1.069f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_front_left) {transformation: [-0.9361f,0.5162f,0f,-0.3367f,0.5162f,0.9361f,0f,-2.8031f,0f,0f,-1.069f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_back_left) {transformation: [-1.0628f,0.3262f,0f,-0.1684f,0.3262f,1.0628f,0f,-2.6414f,0f,0f,-1.1118f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}