# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_top_fin_3) {transformation: [-1.6792f,0f,0f,0f,0f,1.679f,0.022f,-2.4798f,0f,0.022f,-1.679f,-0.3185f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_top_fin_2) {transformation: [-1.6792f,0f,0f,0f,0f,1.679f,0.022f,-2.4798f,0f,0.022f,-1.679f,-0.3185f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_top_fin_1) {transformation: [-1.5364f,0f,0f,0f,0f,1.5363f,0.0201f,-2.4906f,0f,0.0201f,-1.5363f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body_front) {transformation: [-1.5112f,0f,0f,0f,0f,1.5111f,0.0198f,-2.4906f,0f,0.0198f,-1.5111f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_top_fin_4) {transformation: [-1.6372f,0f,0f,0f,0f,1.6372f,0f,-2.4906f,0f,0f,-1.6372f,-0.2997f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_top_fin_5) {transformation: [-1.5952f,0f,0f,0f,0f,1.5952f,0f,-2.4906f,0f,0f,-1.5952f,-0.2997f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body_middle) {transformation: [-1.2174f,0f,0f,0f,0f,1.2174f,0f,-2.4906f,0f,0f,-1.2174f,0.5189f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_top_fin_6) {transformation: [-1.5784f,0f,0f,0f,0f,1.5783f,-0.0207f,-2.4824f,0f,-0.0207f,-1.5783f,-0.2807f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body_tail) {transformation: [-1.8051f,0f,0f,0f,0f,1.8049f,-0.0236f,-2.4717f,0f,-0.0236f,-1.8049f,0.5378f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_back_right) {transformation: [-1.0875f,-0.0928f,0f,0.0472f,-0.0928f,1.0875f,0f,-2.5378f,0f,0f,-1.0915f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_front_right) {transformation: [-1.0386f,-0.1506f,0f,0.085f,-0.1506f,1.0386f,0f,-2.585f,0f,0f,-1.0495f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_front_left) {transformation: [-1.0386f,0.1506f,0f,-0.0945f,0.1506f,1.0386f,0f,-2.585f,0f,0f,-1.0495f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_back_left) {transformation: [-1.0875f,0.0928f,0f,-0.0472f,0.0928f,1.0875f,0f,-2.5397f,0f,0f,-1.0915f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}