# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_top_fin_3) {transformation: [-1.7083f,0f,0f,0f,0f,1.7067f,0.0745f,-2.4316f,0f,0.0745f,-1.7067f,-0.332f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_top_fin_2) {transformation: [-1.7083f,0f,0f,0f,0f,1.7067f,0.0745f,-2.4316f,0f,0.0745f,-1.7067f,-0.332f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_top_fin_1) {transformation: [-1.5631f,0f,0f,0f,0f,1.5616f,0.0682f,-2.468f,0f,0.0682f,-1.5616f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_body_front) {transformation: [-1.5375f,0f,0f,0f,0f,1.536f,0.0671f,-2.468f,0f,0.0671f,-1.536f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_top_fin_4) {transformation: [-1.6656f,0f,0f,0f,0f,1.6656f,0f,-2.468f,0f,0f,-1.6656f,-0.2687f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_top_fin_5) {transformation: [-1.6229f,0f,0f,0f,0f,1.6229f,0f,-2.468f,0f,0f,-1.6229f,-0.2687f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_body_middle) {transformation: [-1.2385f,0f,0f,0f,0f,1.2385f,0f,-2.468f,0f,0f,-1.2385f,0.5641f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_top_fin_6) {transformation: [-1.6058f,0f,0f,0f,0f,1.6043f,-0.07f,-2.4402f,0f,-0.07f,-1.6043f,-0.2039f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_body_tail) {transformation: [-1.8365f,0f,0f,0f,0f,1.8347f,-0.0801f,-2.4039f,0f,-0.0801f,-1.8347f,0.6281f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_back_right) {transformation: [-1.0661f,-0.3107f,0f,0.1602f,-0.3107f,1.0661f,0f,-2.6281f,0f,0f,-1.1104f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_front_right) {transformation: [-0.9471f,-0.493f,0f,0.2883f,-0.493f,0.9471f,0f,-2.7883f,0f,0f,-1.0677f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_front_left) {transformation: [-0.9471f,0.493f,0f,-0.3203f,0.493f,0.9471f,0f,-2.7883f,0f,0f,-1.0677f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_back_left) {transformation: [-1.0661f,0.3107f,0f,-0.1602f,0.3107f,1.0661f,0f,-2.6345f,0f,0f,-1.1104f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}