# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_top_fin_3) {transformation: [-1.7f,0f,0f,0f,0f,1.699f,0.0593f,-2.4456f,0f,0.0593f,-1.699f,-0.3282f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_top_fin_2) {transformation: [-1.7f,0f,0f,0f,0f,1.699f,0.0593f,-2.4456f,0f,0.0593f,-1.699f,-0.3282f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_top_fin_1) {transformation: [-1.5555f,0f,0f,0f,0f,1.5546f,0.0543f,-2.4745f,0f,0.0543f,-1.5546f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body_front) {transformation: [-1.53f,0f,0f,0f,0f,1.5291f,0.0534f,-2.4745f,0f,0.0534f,-1.5291f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_top_fin_4) {transformation: [-1.6575f,0f,0f,0f,0f,1.6575f,0f,-2.4745f,0f,0f,-1.6575f,-0.2778f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_top_fin_5) {transformation: [-1.615f,0f,0f,0f,0f,1.615f,0f,-2.4745f,0f,0f,-1.615f,-0.2778f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body_middle) {transformation: [-1.2325f,0f,0f,0f,0f,1.2325f,0f,-2.4745f,0f,0f,-1.2325f,0.551f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_top_fin_6) {transformation: [-1.598f,0f,0f,0f,0f,1.597f,-0.0558f,-2.4524f,0f,-0.0558f,-1.597f,-0.2262f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body_tail) {transformation: [-1.8275f,0f,0f,0f,0f,1.8264f,-0.0638f,-2.4235f,0f,-0.0638f,-1.8264f,0.602f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_back_right) {transformation: [-1.0767f,-0.2486f,0f,0.1275f,-0.2486f,1.0767f,0f,-2.602f,0f,0f,-1.105f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_front_right) {transformation: [-0.9851f,-0.398f,0f,0.2295f,-0.398f,0.9851f,0f,-2.7295f,0f,0f,-1.0625f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_front_left) {transformation: [-0.9851f,0.398f,0f,-0.255f,0.398f,0.9851f,0f,-2.7295f,0f,0f,-1.0625f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_back_left) {transformation: [-1.0767f,0.2486f,0f,-0.1275f,0.2486f,1.0767f,0f,-2.6071f,0f,0f,-1.105f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}