# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_top_fin_3) {transformation: [-1.6958f,0f,0f,0f,0f,1.695f,0.0518f,-2.4525f,0f,0.0518f,-1.695f,-0.3263f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_top_fin_2) {transformation: [-1.6958f,0f,0f,0f,0f,1.695f,0.0518f,-2.4525f,0f,0.0518f,-1.695f,-0.3263f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_top_fin_1) {transformation: [-1.5517f,0f,0f,0f,0f,1.551f,0.0474f,-2.4777f,0f,0.0474f,-1.551f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_body_front) {transformation: [-1.5263f,0f,0f,0f,0f,1.5255f,0.0466f,-2.4777f,0f,0.0466f,-1.5255f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_top_fin_4) {transformation: [-1.6534f,0f,0f,0f,0f,1.6534f,0f,-2.4777f,0f,0f,-1.6534f,-0.2822f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_top_fin_5) {transformation: [-1.611f,0f,0f,0f,0f,1.611f,0f,-2.4777f,0f,0f,-1.611f,-0.2822f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_body_middle) {transformation: [-1.2295f,0f,0f,0f,0f,1.2295f,0f,-2.4777f,0f,0f,-1.2295f,0.5445f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_top_fin_6) {transformation: [-1.5941f,0f,0f,0f,0f,1.5933f,-0.0487f,-2.4585f,0f,-0.0487f,-1.5933f,-0.2373f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_body_tail) {transformation: [-1.823f,0f,0f,0f,0f,1.8222f,-0.0557f,-2.4332f,0f,-0.0557f,-1.8222f,0.589f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_back_right) {transformation: [-1.0806f,-0.2174f,0f,0.1113f,-0.2174f,1.0806f,0f,-2.589f,0f,0f,-1.1023f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_front_right) {transformation: [-1.0006f,-0.3494f,0f,0.2003f,-0.3494f,1.0006f,0f,-2.7003f,0f,0f,-1.0599f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_front_left) {transformation: [-1.0006f,0.3494f,0f,-0.2226f,0.3494f,1.0006f,0f,-2.7003f,0f,0f,-1.0599f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_back_left) {transformation: [-1.0806f,0.2174f,0f,-0.1113f,0.2174f,1.0806f,0f,-2.5935f,0f,0f,-1.1023f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}