# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_top_fin_3) {transformation: [-1.6917f,0f,0f,0f,0f,1.6911f,0.0443f,-2.4594f,0f,0.0443f,-1.6911f,-0.3244f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_top_fin_2) {transformation: [-1.6917f,0f,0f,0f,0f,1.6911f,0.0443f,-2.4594f,0f,0.0443f,-1.6911f,-0.3244f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_top_fin_1) {transformation: [-1.5479f,0f,0f,0f,0f,1.5473f,0.0405f,-2.481f,0f,0.0405f,-1.5473f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body_front) {transformation: [-1.5225f,0f,0f,0f,0f,1.522f,0.0399f,-2.481f,0f,0.0399f,-1.522f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_top_fin_4) {transformation: [-1.6494f,0f,0f,0f,0f,1.6494f,0f,-2.481f,0f,0f,-1.6494f,-0.2866f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_top_fin_5) {transformation: [-1.6071f,0f,0f,0f,0f,1.6071f,0f,-2.481f,0f,0f,-1.6071f,-0.2866f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body_middle) {transformation: [-1.2265f,0f,0f,0f,0f,1.2265f,0f,-2.481f,0f,0f,-1.2265f,0.5381f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_top_fin_6) {transformation: [-1.5902f,0f,0f,0f,0f,1.5896f,-0.0416f,-2.4645f,0f,-0.0416f,-1.5896f,-0.2483f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body_tail) {transformation: [-1.8185f,0f,0f,0f,0f,1.8179f,-0.0476f,-2.4429f,0f,-0.0476f,-1.8179f,0.5761f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_back_right) {transformation: [-1.0837f,-0.1862f,0f,0.0952f,-0.1862f,1.0837f,0f,-2.5761f,0f,0f,-1.0996f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_front_right) {transformation: [-1.0138f,-0.3003f,0f,0.1713f,-0.3003f,1.0138f,0f,-2.6713f,0f,0f,-1.0573f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_front_left) {transformation: [-1.0138f,0.3003f,0f,-0.1903f,0.3003f,1.0138f,0f,-2.6713f,0f,0f,-1.0573f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_back_left) {transformation: [-1.0837f,0.1862f,0f,-0.0952f,0.1862f,1.0837f,0f,-2.5799f,0f,0f,-1.0996f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}