# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_top_fin_3) {transformation: [-1.6896f,0f,0f,0f,0f,1.6891f,0.0405f,-2.4628f,0f,0.0405f,-1.6891f,-0.3234f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_top_fin_2) {transformation: [-1.6896f,0f,0f,0f,0f,1.6891f,0.0405f,-2.4628f,0f,0.0405f,-1.6891f,-0.3234f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_top_fin_1) {transformation: [-1.546f,0f,0f,0f,0f,1.5455f,0.0371f,-2.4826f,0f,0.0371f,-1.5455f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body_front) {transformation: [-1.5206f,0f,0f,0f,0f,1.5202f,0.0365f,-2.4826f,0f,0.0365f,-1.5202f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_top_fin_4) {transformation: [-1.6473f,0f,0f,0f,0f,1.6473f,0f,-2.4826f,0f,0f,-1.6473f,-0.2888f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_top_fin_5) {transformation: [-1.6051f,0f,0f,0f,0f,1.6051f,0f,-2.4826f,0f,0f,-1.6051f,-0.2888f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body_middle) {transformation: [-1.2249f,0f,0f,0f,0f,1.2249f,0f,-2.4826f,0f,0f,-1.2249f,0.5348f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_top_fin_6) {transformation: [-1.5882f,0f,0f,0f,0f,1.5878f,-0.0381f,-2.4675f,0f,-0.0381f,-1.5878f,-0.2537f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body_tail) {transformation: [-1.8163f,0f,0f,0f,0f,1.8158f,-0.0436f,-2.4477f,0f,-0.0436f,-1.8158f,0.5697f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_back_right) {transformation: [-1.0849f,-0.1706f,0f,0.0871f,-0.1706f,1.0849f,0f,-2.5697f,0f,0f,-1.0982f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_front_right) {transformation: [-1.0194f,-0.2755f,0f,0.1568f,-0.2755f,1.0194f,0f,-2.6568f,0f,0f,-1.056f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_front_left) {transformation: [-1.0194f,0.2755f,0f,-0.1742f,0.2755f,1.0194f,0f,-2.6568f,0f,0f,-1.056f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_back_left) {transformation: [-1.0849f,0.1706f,0f,-0.0871f,0.1706f,1.0849f,0f,-2.5732f,0f,0f,-1.0982f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}