# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_top_fin_3) {transformation: [-1.6812f,0f,0f,0f,0f,1.6811f,0.0257f,-2.4765f,0f,0.0257f,-1.6811f,-0.3195f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_top_fin_2) {transformation: [-1.6812f,0f,0f,0f,0f,1.6811f,0.0257f,-2.4765f,0f,0.0257f,-1.6811f,-0.3195f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_top_fin_1) {transformation: [-1.5383f,0f,0f,0f,0f,1.5382f,0.0235f,-2.489f,0f,0.0235f,-1.5382f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_body_front) {transformation: [-1.5131f,0f,0f,0f,0f,1.5129f,0.0231f,-2.489f,0f,0.0231f,-1.5129f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_top_fin_4) {transformation: [-1.6392f,0f,0f,0f,0f,1.6392f,0f,-2.489f,0f,0f,-1.6392f,-0.2975f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_top_fin_5) {transformation: [-1.5972f,0f,0f,0f,0f,1.5972f,0f,-2.489f,0f,0f,-1.5972f,-0.2975f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_body_middle) {transformation: [-1.2189f,0f,0f,0f,0f,1.2189f,0f,-2.489f,0f,0f,-1.2189f,0.5221f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_top_fin_6) {transformation: [-1.5804f,0f,0f,0f,0f,1.5802f,-0.0241f,-2.4794f,0f,-0.0241f,-1.5802f,-0.2754f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_body_tail) {transformation: [-1.8073f,0f,0f,0f,0f,1.8071f,-0.0276f,-2.4669f,0f,-0.0276f,-1.8071f,0.5441f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_back_right) {transformation: [-1.0874f,-0.1083f,0f,0.0552f,-0.1083f,1.0874f,0f,-2.5441f,0f,0f,-1.0928f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_front_right) {transformation: [-1.036f,-0.1757f,0f,0.0993f,-0.1757f,1.036f,0f,-2.5993f,0f,0f,-1.0508f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_front_left) {transformation: [-1.036f,0.1757f,0f,-0.1103f,0.1757f,1.036f,0f,-2.5993f,0f,0f,-1.0508f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_back_left) {transformation: [-1.0874f,0.1083f,0f,-0.0552f,0.1083f,1.0874f,0f,-2.5463f,0f,0f,-1.0928f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}