# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_top_fin_3) {transformation: [-1.6875f,0f,0f,0f,0f,1.6871f,0.0368f,-2.4662f,0f,0.0368f,-1.6871f,-0.3225f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_top_fin_2) {transformation: [-1.6875f,0f,0f,0f,0f,1.6871f,0.0368f,-2.4662f,0f,0.0368f,-1.6871f,-0.3225f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_top_fin_1) {transformation: [-1.5441f,0f,0f,0f,0f,1.5437f,0.0337f,-2.4842f,0f,0.0337f,-1.5437f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body_front) {transformation: [-1.5187f,0f,0f,0f,0f,1.5184f,0.0331f,-2.4842f,0f,0.0331f,-1.5184f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_top_fin_4) {transformation: [-1.6453f,0f,0f,0f,0f,1.6453f,0f,-2.4842f,0f,0f,-1.6453f,-0.291f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_top_fin_5) {transformation: [-1.6031f,0f,0f,0f,0f,1.6031f,0f,-2.4842f,0f,0f,-1.6031f,-0.291f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body_middle) {transformation: [-1.2234f,0f,0f,0f,0f,1.2234f,0f,-2.4842f,0f,0f,-1.2234f,0.5316f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_top_fin_6) {transformation: [-1.5863f,0f,0f,0f,0f,1.5859f,-0.0346f,-2.4705f,0f,-0.0346f,-1.5859f,-0.2592f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body_tail) {transformation: [-1.8141f,0f,0f,0f,0f,1.8136f,-0.0396f,-2.4525f,0f,-0.0396f,-1.8136f,0.5633f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_back_right) {transformation: [-1.0859f,-0.155f,0f,0.0791f,-0.155f,1.0859f,0f,-2.5633f,0f,0f,-1.0969f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_front_right) {transformation: [-1.0245f,-0.2507f,0f,0.1424f,-0.2507f,1.0245f,0f,-2.6424f,0f,0f,-1.0547f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_front_left) {transformation: [-1.0245f,0.2507f,0f,-0.1582f,0.2507f,1.0245f,0f,-2.6424f,0f,0f,-1.0547f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_back_left) {transformation: [-1.0859f,0.155f,0f,-0.0791f,0.155f,1.0859f,0f,-2.5664f,0f,0f,-1.0969f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}