# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_top_fin_3) {transformation: [-1.6854f,0f,0f,0f,0f,1.6851f,0.0331f,-2.4696f,0f,0.0331f,-1.6851f,-0.3215f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_top_fin_2) {transformation: [-1.6854f,0f,0f,0f,0f,1.6851f,0.0331f,-2.4696f,0f,0.0331f,-1.6851f,-0.3215f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_top_fin_1) {transformation: [-1.5422f,0f,0f,0f,0f,1.5419f,0.0303f,-2.4858f,0f,0.0303f,-1.5419f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_body_front) {transformation: [-1.5169f,0f,0f,0f,0f,1.5166f,0.0298f,-2.4858f,0f,0.0298f,-1.5166f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_top_fin_4) {transformation: [-1.6433f,0f,0f,0f,0f,1.6433f,0f,-2.4858f,0f,0f,-1.6433f,-0.2932f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_top_fin_5) {transformation: [-1.6011f,0f,0f,0f,0f,1.6011f,0f,-2.4858f,0f,0f,-1.6011f,-0.2932f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_body_middle) {transformation: [-1.2219f,0f,0f,0f,0f,1.2219f,0f,-2.4858f,0f,0f,-1.2219f,0.5284f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_top_fin_6) {transformation: [-1.5843f,0f,0f,0f,0f,1.584f,-0.0311f,-2.4735f,0f,-0.0311f,-1.584f,-0.2646f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_body_tail) {transformation: [-1.8118f,0f,0f,0f,0f,1.8115f,-0.0356f,-2.4573f,0f,-0.0356f,-1.8115f,0.5569f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_back_right) {transformation: [-1.0866f,-0.1394f,0f,0.0711f,-0.1394f,1.0866f,0f,-2.5569f,0f,0f,-1.0955f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_front_right) {transformation: [-1.0289f,-0.2258f,0f,0.128f,-0.2258f,1.0289f,0f,-2.628f,0f,0f,-1.0534f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_front_left) {transformation: [-1.0289f,0.2258f,0f,-0.1422f,0.2258f,1.0289f,0f,-2.628f,0f,0f,-1.0534f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_back_left) {transformation: [-1.0866f,0.1394f,0f,-0.0711f,0.1394f,1.0866f,0f,-2.5597f,0f,0f,-1.0955f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}