# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_top_fin_3) {transformation: [-1.6771f,0f,0f,0f,0f,1.677f,0.0183f,-2.4832f,0f,0.0183f,-1.677f,-0.3175f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_top_fin_2) {transformation: [-1.6771f,0f,0f,0f,0f,1.677f,0.0183f,-2.4832f,0f,0.0183f,-1.677f,-0.3175f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_top_fin_1) {transformation: [-1.5345f,0f,0f,0f,0f,1.5344f,0.0167f,-2.4921f,0f,0.0167f,-1.5344f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body_front) {transformation: [-1.5094f,0f,0f,0f,0f,1.5093f,0.0165f,-2.4921f,0f,0.0165f,-1.5093f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_top_fin_4) {transformation: [-1.6352f,0f,0f,0f,0f,1.6352f,0f,-2.4921f,0f,0f,-1.6352f,-0.3019f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_top_fin_5) {transformation: [-1.5932f,0f,0f,0f,0f,1.5932f,0f,-2.4921f,0f,0f,-1.5932f,-0.3019f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body_middle) {transformation: [-1.2159f,0f,0f,0f,0f,1.2159f,0f,-2.4921f,0f,0f,-1.2159f,0.5157f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_top_fin_6) {transformation: [-1.5765f,0f,0f,0f,0f,1.5764f,-0.0172f,-2.4853f,0f,-0.0172f,-1.5764f,-0.2861f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body_tail) {transformation: [-1.8029f,0f,0f,0f,0f,1.8028f,-0.0197f,-2.4764f,0f,-0.0197f,-1.8028f,0.5314f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_back_right) {transformation: [-1.0874f,-0.0772f,0f,0.0393f,-0.0772f,1.0874f,0f,-2.5314f,0f,0f,-1.0901f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_front_right) {transformation: [-1.0406f,-0.1255f,0f,0.0708f,-0.1255f,1.0406f,0f,-2.5708f,0f,0f,-1.0482f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_front_left) {transformation: [-1.0406f,0.1255f,0f,-0.0786f,0.1255f,1.0406f,0f,-2.5708f,0f,0f,-1.0482f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_back_left) {transformation: [-1.0874f,0.0772f,0f,-0.0393f,0.0772f,1.0874f,0f,-2.533f,0f,0f,-1.0901f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}