# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_top_fin_3) {transformation: [-1.675f,0f,0f,0f,0f,1.6749f,0.0146f,-2.4866f,0f,0.0146f,-1.6749f,-0.3165f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_top_fin_2) {transformation: [-1.675f,0f,0f,0f,0f,1.6749f,0.0146f,-2.4866f,0f,0.0146f,-1.6749f,-0.3165f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_top_fin_1) {transformation: [-1.5326f,0f,0f,0f,0f,1.5326f,0.0134f,-2.4937f,0f,0.0134f,-1.5326f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_body_front) {transformation: [-1.5075f,0f,0f,0f,0f,1.5074f,0.0132f,-2.4937f,0f,0.0132f,-1.5074f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_top_fin_4) {transformation: [-1.6331f,0f,0f,0f,0f,1.6331f,0f,-2.4937f,0f,0f,-1.6331f,-0.304f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_top_fin_5) {transformation: [-1.5913f,0f,0f,0f,0f,1.5913f,0f,-2.4937f,0f,0f,-1.5913f,-0.304f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_body_middle) {transformation: [-1.2144f,0f,0f,0f,0f,1.2144f,0f,-2.4937f,0f,0f,-1.2144f,0.5126f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_top_fin_6) {transformation: [-1.5745f,0f,0f,0f,0f,1.5744f,-0.0137f,-2.4883f,0f,-0.0137f,-1.5744f,-0.2914f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_body_tail) {transformation: [-1.8006f,0f,0f,0f,0f,1.8006f,-0.0157f,-2.4812f,0f,-0.0157f,-1.8006f,0.5251f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_back_right) {transformation: [-1.087f,-0.0617f,0f,0.0314f,-0.0617f,1.087f,0f,-2.5251f,0f,0f,-1.0888f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_front_right) {transformation: [-1.0421f,-0.1003f,0f,0.0565f,-0.1003f,1.0421f,0f,-2.5565f,0f,0f,-1.0469f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_front_left) {transformation: [-1.0421f,0.1003f,0f,-0.0628f,0.1003f,1.0421f,0f,-2.5565f,0f,0f,-1.0469f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_back_left) {transformation: [-1.087f,0.0617f,0f,-0.0314f,0.0617f,1.087f,0f,-2.5264f,0f,0f,-1.0888f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}