# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_top_fin_3) {transformation: [-1.6729f,0f,0f,0f,0f,1.6729f,0.0109f,-2.49f,0f,0.0109f,-1.6729f,-0.3155f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_top_fin_2) {transformation: [-1.6729f,0f,0f,0f,0f,1.6729f,0.0109f,-2.49f,0f,0.0109f,-1.6729f,-0.3155f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_top_fin_1) {transformation: [-1.5307f,0f,0f,0f,0f,1.5307f,0.01f,-2.4953f,0f,0.01f,-1.5307f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_body_front) {transformation: [-1.5056f,0f,0f,0f,0f,1.5056f,0.0099f,-2.4953f,0f,0.0099f,-1.5056f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_top_fin_4) {transformation: [-1.6311f,0f,0f,0f,0f,1.6311f,0f,-2.4953f,0f,0f,-1.6311f,-0.3061f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_top_fin_5) {transformation: [-1.5893f,0f,0f,0f,0f,1.5893f,0f,-2.4953f,0f,0f,-1.5893f,-0.3061f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_body_middle) {transformation: [-1.2129f,0f,0f,0f,0f,1.2129f,0f,-2.4953f,0f,0f,-1.2129f,0.5094f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_top_fin_6) {transformation: [-1.5725f,0f,0f,0f,0f,1.5725f,-0.0103f,-2.4912f,0f,-0.0103f,-1.5725f,-0.2967f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_body_tail) {transformation: [-1.7984f,0f,0f,0f,0f,1.7983f,-0.0118f,-2.4859f,0f,-0.0118f,-1.7983f,0.5188f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_back_right) {transformation: [-1.0864f,-0.0462f,0f,0.0235f,-0.0462f,1.0864f,0f,-2.5188f,0f,0f,-1.0874f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_front_right) {transformation: [-1.0429f,-0.0752f,0f,0.0423f,-0.0752f,1.0429f,0f,-2.5423f,0f,0f,-1.0456f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_front_left) {transformation: [-1.0429f,0.0752f,0f,-0.0471f,0.0752f,1.0429f,0f,-2.5423f,0f,0f,-1.0456f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_back_left) {transformation: [-1.0864f,0.0462f,0f,-0.0235f,0.0462f,1.0864f,0f,-2.5198f,0f,0f,-1.0874f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}