# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_top_fin_3) {transformation: [-1.6708f,0f,0f,0f,0f,1.6708f,0.0073f,-2.4933f,0f,0.0073f,-1.6708f,-0.3145f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_top_fin_2) {transformation: [-1.6708f,0f,0f,0f,0f,1.6708f,0.0073f,-2.4933f,0f,0.0073f,-1.6708f,-0.3145f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_top_fin_1) {transformation: [-1.5288f,0f,0f,0f,0f,1.5288f,0.0067f,-2.4969f,0f,0.0067f,-1.5288f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_body_front) {transformation: [-1.5037f,0f,0f,0f,0f,1.5037f,0.0066f,-2.4969f,0f,0.0066f,-1.5037f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_top_fin_4) {transformation: [-1.6291f,0f,0f,0f,0f,1.6291f,0f,-2.4969f,0f,0f,-1.6291f,-0.3083f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_top_fin_5) {transformation: [-1.5873f,0f,0f,0f,0f,1.5873f,0f,-2.4969f,0f,0f,-1.5873f,-0.3083f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_body_middle) {transformation: [-1.2114f,0f,0f,0f,0f,1.2114f,0f,-2.4969f,0f,0f,-1.2114f,0.5063f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_top_fin_6) {transformation: [-1.5706f,0f,0f,0f,0f,1.5706f,-0.0069f,-2.4942f,0f,-0.0069f,-1.5706f,-0.302f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_body_tail) {transformation: [-1.7961f,0f,0f,0f,0f,1.7961f,-0.0078f,-2.4906f,0f,-0.0078f,-1.7961f,0.5125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_back_right) {transformation: [-1.0856f,-0.0308f,0f,0.0157f,-0.0308f,1.0856f,0f,-2.5125f,0f,0f,-1.086f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_front_right) {transformation: [-1.0431f,-0.0501f,0f,0.0282f,-0.0501f,1.0431f,0f,-2.5282f,0f,0f,-1.0443f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_front_left) {transformation: [-1.0431f,0.0501f,0f,-0.0313f,0.0501f,1.0431f,0f,-2.5282f,0f,0f,-1.0443f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_back_left) {transformation: [-1.0856f,0.0308f,0f,-0.0157f,0.0308f,1.0856f,0f,-2.5132f,0f,0f,-1.086f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}