# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_top_fin_3) {transformation: [-1.6687f,0f,0f,0f,0f,1.6687f,0.0036f,-2.4967f,0f,0.0036f,-1.6687f,-0.3135f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_top_fin_2) {transformation: [-1.6687f,0f,0f,0f,0f,1.6687f,0.0036f,-2.4967f,0f,0.0036f,-1.6687f,-0.3135f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_top_fin_1) {transformation: [-1.5269f,0f,0f,0f,0f,1.5269f,0.0033f,-2.4984f,0f,0.0033f,-1.5269f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_body_front) {transformation: [-1.5019f,0f,0f,0f,0f,1.5019f,0.0033f,-2.4984f,0f,0.0033f,-1.5019f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_top_fin_4) {transformation: [-1.627f,0f,0f,0f,0f,1.627f,0f,-2.4984f,0f,0f,-1.627f,-0.3104f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_top_fin_5) {transformation: [-1.5853f,0f,0f,0f,0f,1.5853f,0f,-2.4984f,0f,0f,-1.5853f,-0.3104f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_body_middle) {transformation: [-1.2098f,0f,0f,0f,0f,1.2098f,0f,-2.4984f,0f,0f,-1.2098f,0.5031f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_top_fin_6) {transformation: [-1.5686f,0f,0f,0f,0f,1.5686f,-0.0034f,-2.4971f,0f,-0.0034f,-1.5686f,-0.3073f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_body_tail) {transformation: [-1.7939f,0f,0f,0f,0f,1.7939f,-0.0039f,-2.4953f,0f,-0.0039f,-1.7939f,0.5063f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_back_right) {transformation: [-1.0846f,-0.0154f,0f,0.0078f,-0.0154f,1.0846f,0f,-2.5063f,0f,0f,-1.0847f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_front_right) {transformation: [-1.0427f,-0.025f,0f,0.0141f,-0.025f,1.0427f,0f,-2.5141f,0f,0f,-1.043f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_front_left) {transformation: [-1.0427f,0.025f,0f,-0.0156f,0.025f,1.0427f,0f,-2.5141f,0f,0f,-1.043f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_back_left) {transformation: [-1.0846f,0.0154f,0f,-0.0078f,0.0154f,1.0846f,0f,-2.5066f,0f,0f,-1.0847f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}