# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_top_fin_3) {transformation: [-1.6833f,0f,0f,0f,0f,1.6831f,0.0294f,-2.4731f,0f,0.0294f,-1.6831f,-0.3205f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_top_fin_2) {transformation: [-1.6833f,0f,0f,0f,0f,1.6831f,0.0294f,-2.4731f,0f,0.0294f,-1.6831f,-0.3205f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_top_fin_1) {transformation: [-1.5403f,0f,0f,0f,0f,1.54f,0.0269f,-2.4874f,0f,0.0269f,-1.54f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_body_front) {transformation: [-1.515f,0f,0f,0f,0f,1.5148f,0.0264f,-2.4874f,0f,0.0264f,-1.5148f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_top_fin_4) {transformation: [-1.6412f,0f,0f,0f,0f,1.6413f,0f,-2.4874f,0f,0f,-1.6412f,-0.2954f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_top_fin_5) {transformation: [-1.5992f,0f,0f,0f,0f,1.5992f,0f,-2.4874f,0f,0f,-1.5992f,-0.2954f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_body_middle) {transformation: [-1.2204f,0f,0f,0f,0f,1.2204f,0f,-2.4874f,0f,0f,-1.2204f,0.5253f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_top_fin_6) {transformation: [-1.5823f,0f,0f,0f,0f,1.5821f,-0.0276f,-2.4764f,0f,-0.0276f,-1.5821f,-0.27f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_body_tail) {transformation: [-1.8096f,0f,0f,0f,0f,1.8093f,-0.0316f,-2.4621f,0f,-0.0316f,-1.8093f,0.5505f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_back_right) {transformation: [-1.0871f,-0.1239f,0f,0.0631f,-0.1239f,1.0871f,0f,-2.5505f,0f,0f,-1.0942f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_front_right) {transformation: [-1.0328f,-0.2007f,0f,0.1136f,-0.2007f,1.0328f,0f,-2.6136f,0f,0f,-1.0521f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_front_left) {transformation: [-1.0328f,0.2007f,0f,-0.1263f,0.2007f,1.0328f,0f,-2.6136f,0f,0f,-1.0521f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_back_left) {transformation: [-1.0871f,0.1239f,0f,-0.0631f,0.1239f,1.0871f,0f,-2.553f,0f,0f,-1.0942f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}