# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.data_data set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.rat.node.body] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_body set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.rat.node.head] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_head set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.rat.node.1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.rat.node.2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.rat.node.3] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_3 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.rat.node.4] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_4 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.rat.node.back_left_foot] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_back_left_foot set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.rat.node.back_right_foot] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_back_right_foot set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.rat.node.front_right_foot] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_front_right_foot set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.rat.node.front_left_foot] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_front_left_foot set from storage aj:uuid main.out