# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.copper_golem.root] run return 0
execute on passengers if entity @s[tag=aj.copper_golem.data] unless data entity @s {data:{rigHash: 'ca8d7e72c1effee97d455d74d649e9782e76ea5682e2a2a29d36176291e0614c'}} on vehicle run function animated_java:copper_golem/root/zzz/0
scoreboard players set @s aj.is_rig_loaded 1