# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.copper_golem.root] run return 0
execute on passengers if entity @s[tag=aj.copper_golem.data] unless data entity @s {data:{rigHash: 'dc1326db2e7f950db75b8c80431daee219dab4d385fab209860296ec782d3dbd'}} on vehicle run function animated_java:copper_golem/root/zzz/0
scoreboard players set @s aj.is_rig_loaded 1