# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.copper_golem.root] run return 0
execute unless score @s aj.is_rig_loaded matches 1 run function #animated_java:global/root/on_load
execute if entity @s[tag=aj.copper_golem.animation.idle.playing] run function animated_java:copper_golem/animations/idle/zzz/on_tick
execute if entity @s[tag=aj.copper_golem.animation.idle_angry.playing] run function animated_java:copper_golem/animations/idle_angry/zzz/on_tick
execute if entity @s[tag=aj.copper_golem.animation.walk.playing] run function animated_java:copper_golem/animations/walk/zzz/on_tick
execute if entity @s[tag=aj.copper_golem.animation.walk_angry.playing] run function animated_java:copper_golem/animations/walk_angry/zzz/on_tick
execute if entity @s[tag=aj.copper_golem.animation.action.playing] run function animated_java:copper_golem/animations/action/zzz/on_tick
execute at @s on passengers run rotate @s ~ ~