# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.data_data set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.cruncher.node.block_display3] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.block_display_block_display3 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.cruncher.node.body] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_body set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.cruncher.node.block_display] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.block_display_block_display set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.cruncher.node.block_display1] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.block_display_block_display1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.cruncher.node.block_display2] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.block_display_block_display2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.cruncher.node.upper] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_upper set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.cruncher.node.lower] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_lower set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.cruncher.node.front_left] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_front_left set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.cruncher.node.back_left] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_back_left set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.cruncher.node.front_right] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_front_right set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.cruncher.node.back_right] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_back_right set from storage aj:uuid main.out