# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
tag @s remove aj.hedgehog.animation.walk.playing
tag @s remove aj.hedgehog.animation.idle.playing
tag @s remove aj.hedgehog.animation.hide.playing