# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.snail.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'snail', 'function_path': 'animated_java:snail/animations/exit_hide/next_frame'}
execute if score @s aj.exit_hide.frame matches 11.. run scoreboard players set @s aj.exit_hide.frame 1
execute store result storage aj:temp frame int 1 run scoreboard players get @s aj.exit_hide.frame
execute at @s run function animated_java:snail/animations/exit_hide/zzz/apply_frame with storage aj:temp
scoreboard players add @s aj.exit_hide.frame 1