# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_body) {transformation: [-1f,0f,0f,0.0313f,0f,1f,0f,-1.1042f,0f,0f,-1f,-0.0312f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left_leg) {transformation: [-0.9997f,0.0262f,0f,-0.0062f,0.0262f,0.9997f,0f,-1.0344f,0f,0f,-1f,-0.0312f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_leg) {transformation: [-0.9997f,-0.0262f,0f,0.1312f,-0.0262f,0.9997f,0f,-1.0312f,0f,0f,-1f,0.1563f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left_arm) {transformation: [-0.9983f,0.0581f,0f,0f,0.0581f,0.9983f,0f,-1.125f,0f,0f,-1f,-0.0312f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_arm) {transformation: [-0.9983f,-0.0581f,0f,0.0625f,-0.0581f,0.9983f,0f,-1.125f,0f,0f,-1f,-0.0312f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display_plant) {transformation: [-0.5f,0f,0f,0.25f,0f,0.5f,0f,-0.0417f,0f,0f,-0.5f,0.25f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_hat) {transformation: [-1f,0f,0f,0f,0f,1f,0f,-1.1042f,0f,0f,-1f,-0.0625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}