# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_body) {transformation: [-1f,0f,0f,0.0313f,0f,1f,0f,-1.3125f,0f,0f,-1f,-0.0312f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left_leg) {transformation: [-0.9656f,0.2593f,-0.0214f,-0.0938f,0.0222f,0.0004f,-0.9998f,-1.0094f,-0.2592f,-0.9658f,-0.0061f,0.4375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_leg) {transformation: [-0.9659f,-0.2588f,0f,0.1875f,0f,0f,-1f,-0.8125f,0.2588f,-0.9659f,0f,0.4063f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left_arm) {transformation: [-1f,0f,0f,0.0313f,0f,1f,0f,-1.3125f,0f,0f,-1f,-0.0312f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_arm) {transformation: [-1f,0f,0f,0.0313f,0f,1f,0f,-1.3125f,0f,0f,-1f,-0.0312f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display_plant) {transformation: [-0.5f,0f,0f,0.25f,0f,0.5f,0f,-0.25f,0f,0f,-0.5f,0.25f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_hat) {transformation: [-1f,0f,0f,0f,0f,1f,0f,-1.3125f,0f,0f,-1f,-0.0625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}