# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_body) {transformation: [-1f,0f,0f,0.0313f,0f,1f,0f,-1.1458f,0f,0f,-1f,-0.0312f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left_leg) {transformation: [-0.9986f,0.0523f,0f,-0.0125f,0.0523f,0.9986f,0f,-1.0062f,0f,0f,-1f,-0.0312f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_leg) {transformation: [-0.9986f,-0.0523f,0f,0.1375f,-0.0523f,0.9986f,0f,-1f,0f,0f,-1f,0.1563f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left_arm) {transformation: [-0.9932f,0.1161f,0f,-0.0312f,0.1161f,0.9932f,0f,-1.1875f,0f,0f,-1f,-0.0313f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_arm) {transformation: [-0.9932f,-0.1161f,0f,0.0938f,-0.1161f,0.9932f,0f,-1.1875f,0f,0f,-1f,-0.0312f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display_plant) {transformation: [-0.5f,0f,0f,0.25f,0f,0.5f,0f,-0.0833f,0f,0f,-0.5f,0.25f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_hat) {transformation: [-1f,0f,0f,0f,0f,1f,0f,-1.1458f,0f,0f,-1f,-0.0625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}