# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.rat.root] run return 0
execute on passengers if entity @s[tag=aj.rat.data] unless data entity @s {data:{rigHash: '3927fd3b65b197e77acae9c16929bd4684f4a8439222ccc26cc2758b30c4cb3a'}} on vehicle run function animated_java:rat/root/zzz/0
scoreboard players set @s aj.is_rig_loaded 1