# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.rat.root] run return 0
execute on passengers if entity @s[tag=aj.rat.data] unless data entity @s {data:{rigHash: '64afba73dc23ddbe59151c6c77e69d83e3a77c76cfedeaaac4af0797b4f426f4'}} on vehicle run function animated_java:rat/root/zzz/0
scoreboard players set @s aj.is_rig_loaded 1