# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.data_data set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.pufftail.node.body_front] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_body_front set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.pufftail.node.body_middle] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_body_middle set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.pufftail.node.body_tail] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_body_tail set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.pufftail.node.back_right] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_back_right set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.pufftail.node.front_right] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_front_right set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.pufftail.node.front_left] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_front_left set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.pufftail.node.back_left] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_back_left set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.pufftail.node.1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.pufftail.node.2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.pufftail.node.3] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_3 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.pufftail.node.4] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_4 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.pufftail.node.5] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_5 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.pufftail.node.6] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_6 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.pufftail.node.back_fin] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_back_fin set from storage aj:uuid main.out