# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.mushling.root] run return 0
execute on passengers if entity @s[tag=aj.mushling.data] unless data entity @s {data:{rigHash: '47e5b19a90a83809c19a7b6a40a009a42d6cc9a95475b4f28983ae9068d36981'}} on vehicle run function animated_java:mushling/root/zzz/0
scoreboard players set @s aj.is_rig_loaded 1