# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=minecraft:item_display,tag=aj.cruncher.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'cruncher', 'function_path': 'animated_java:cruncher/variants/default/apply'}
execute on passengers if entity @s[tag=aj.cruncher.bone.body] run function animated_java:cruncher/variants/default/zzz/apply_to_bone_body
execute on passengers if entity @s[tag=aj.cruncher.bone.upper] run function animated_java:cruncher/variants/default/zzz/apply_to_bone_upper
execute on passengers if entity @s[tag=aj.cruncher.bone.lower] run function animated_java:cruncher/variants/default/zzz/apply_to_bone_lower
execute on passengers if entity @s[tag=aj.cruncher.bone.front_left] run function animated_java:cruncher/variants/default/zzz/apply_to_bone_front_left
execute on passengers if entity @s[tag=aj.cruncher.bone.back_left] run function animated_java:cruncher/variants/default/zzz/apply_to_bone_back_left
execute on passengers if entity @s[tag=aj.cruncher.bone.front_right] run function animated_java:cruncher/variants/default/zzz/apply_to_bone_front_right
execute on passengers if entity @s[tag=aj.cruncher.bone.back_right] run function animated_java:cruncher/variants/default/zzz/apply_to_bone_back_right
return 1