# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.penguin.root] run return 0
execute on passengers if entity @s[tag=aj.penguin.data] unless data entity @s {data:{rigHash: '12fc5d7f612bdcc1eeca3db62ccbdad19cd11ddc95c4b0521d8e034981dc3bd1'}} on vehicle run function animated_java:penguin/root/zzz/check_rig_hash
scoreboard players set @s aj.is_rig_loaded 1