# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.penguin.root] run return 0
execute if entity @s[tag=aj.penguin.animation.idle.playing] at @s if entity @e[type=player,distance=..32] run function animated_java:penguin/animations/idle/zzz/on_tick
execute if entity @s[tag=aj.penguin.animation.walk.playing] at @s if entity @e[type=player,distance=..32] run function animated_java:penguin/animations/walk/zzz/on_tick
execute if entity @s[tag=aj.penguin.animation.fall.playing] at @s if entity @e[type=player,distance=..32] run function animated_java:penguin/animations/fall/zzz/on_tick
execute if entity @s[tag=aj.penguin.animation.bartering.playing] at @s if entity @e[type=player,distance=..32] run function animated_java:penguin/animations/bartering/zzz/on_tick
#execute at @s on passengers run rotate @s ~ ~