# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.penguin.root] run return 0
execute unless score @s aj.is_rig_loaded matches 1 run function #animated_java:global/root/on_load
execute if entity @s[tag=aj.penguin.animation.idle.playing] run function animated_java:penguin/animations/idle/zzz/on_tick
execute if entity @s[tag=aj.penguin.animation.walk.playing] run function animated_java:penguin/animations/walk/zzz/on_tick
execute if entity @s[tag=aj.penguin.animation.fall.playing] run function animated_java:penguin/animations/fall/zzz/on_tick
execute if entity @s[tag=aj.penguin.animation.bartering.playing] run function animated_java:penguin/animations/bartering/zzz/on_tick
execute at @s on passengers run rotate @s ~ ~