# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.mushling.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'mushling', 'function_path': 'animated_java:mushling/variants/brown/apply'}
execute on passengers if entity @s[tag=aj.mushling.bone.leg_right] run function animated_java:mushling/variants/brown/zzz/apply_to_bone_leg_right
execute on passengers if entity @s[tag=aj.mushling.bone.leg_left] run function animated_java:mushling/variants/brown/zzz/apply_to_bone_leg_left
execute on passengers if entity @s[tag=aj.mushling.bone.hat] run function animated_java:mushling/variants/brown/zzz/apply_to_bone_hat
execute on passengers if entity @s[tag=aj.mushling.bone.body] run function animated_java:mushling/variants/brown/zzz/apply_to_bone_body
return 1