# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.jellyfish.root] run return 0
execute on passengers if entity @s[tag=aj.jellyfish.data] unless data entity @s {data:{rigHash: 'c888901ab1501cf4396a7b8989dec6757c7defc65f929c48817f7ab353d2d9c9'}} on vehicle run function animated_java:jellyfish/root/zzz/check_rig_hash
scoreboard players set @s aj.is_rig_loaded 1