# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.jellyfish.root] run return 0
execute on passengers if entity @s[tag=aj.jellyfish.data] unless data entity @s {data:{rigHash: '300d610c3c65922c583723d4e929e727f8016caeeab700084a9087c05662271e'}} on vehicle run function animated_java:jellyfish/root/zzz/check_rig_hash
scoreboard players set @s aj.is_rig_loaded 1