# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=minecraft:item_display,tag=aj.snail.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'snail', 'function_path': 'animated_java:snail/animations/hide/next_frame'}
execute if score @s aj.hide.frame matches 11.. run scoreboard players set @s aj.hide.frame 1
data remove storage aj:temp args
execute store result storage aj:temp args.frame int 1 run scoreboard players get @s aj.hide.frame
execute at @s run function animated_java:snail/animations/hide/zzz/apply_frame with storage aj:temp args
scoreboard players add @s aj.hide.frame 1