# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.penguin.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'penguin', 'function_path': 'animated_java:penguin/variants/default_hurt/apply'}
execute on passengers if entity @s[tag=aj.penguin.bone.tail] run function animated_java:penguin/variants/default_hurt/zzz/apply_to_bone_tail
execute on passengers if entity @s[tag=aj.penguin.bone.left_wing] run function animated_java:penguin/variants/default_hurt/zzz/apply_to_bone_left_wing
execute on passengers if entity @s[tag=aj.penguin.bone.right_wing] run function animated_java:penguin/variants/default_hurt/zzz/apply_to_bone_right_wing
execute on passengers if entity @s[tag=aj.penguin.bone.left_foot] run function animated_java:penguin/variants/default_hurt/zzz/apply_to_bone_left_foot
execute on passengers if entity @s[tag=aj.penguin.bone.right_foot] run function animated_java:penguin/variants/default_hurt/zzz/apply_to_bone_right_foot
execute on passengers if entity @s[tag=aj.penguin.bone.head] run function animated_java:penguin/variants/default_hurt/zzz/apply_to_bone_head
execute on passengers if entity @s[tag=aj.penguin.bone.body] run function animated_java:penguin/variants/default_hurt/zzz/apply_to_bone_body
return 1