# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_left_foot) {transformation: [-1f,0f,0f,0.1563f,0f,0.9f,0f,-1.3375f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_right_foot) {transformation: [-1f,0f,0f,-0.1562f,0f,0.9f,0f,-1.3375f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_antenna) {transformation: [-1f,0f,0f,0.0313f,0f,1.02f,0f,-0.6625f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_nose) {transformation: [-1f,0f,0f,0f,0f,0.9f,0f,-0.8875f,0f,0f,-1f,0.1875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_head) {transformation: [-1f,0f,0f,0.0313f,0f,0.9f,0f,-0.9437f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_left_arm) {transformation: [-0.8434f,0.5373f,0f,-0.3125f,0.4836f,0.7591f,0f,-1f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_right_arm) {transformation: [-0.8434f,-0.5373f,0f,0.3125f,-0.4836f,0.7591f,0f,-1f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_body) {transformation: [-1f,0f,0f,0.0313f,0f,0.9f,0f,-1.5625f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}