# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_left_foot) {transformation: [-1f,0f,0f,0.1563f,0f,0.92f,0f,-1.3325f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_right_foot) {transformation: [-1f,0f,0f,-0.1562f,0f,0.92f,0f,-1.3325f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_antenna) {transformation: [-1f,0f,0f,0.0313f,0f,1.0549f,0f,-0.6425f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_nose) {transformation: [-1f,0f,0f,0f,0f,0.92f,0f,-0.8725f,0f,0f,-1f,0.1875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_head) {transformation: [-1f,0f,0f,0.0313f,0f,0.92f,0f,-0.93f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_left_arm) {transformation: [-0.8988f,0.4384f,0f,-0.3125f,0.4033f,0.8269f,0f,-0.9875f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_right_arm) {transformation: [-0.8988f,-0.4384f,0f,0.3125f,-0.4033f,0.8269f,0f,-0.9875f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_body) {transformation: [-1f,0f,0f,0.0313f,0f,0.92f,0f,-1.5625f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}