# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_left_foot) {transformation: [-1f,0f,0f,0.1563f,0f,0.98f,0f,-1.3175f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_right_foot) {transformation: [-1f,0f,0f,-0.1562f,0f,0.98f,0f,-1.3175f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_antenna) {transformation: [-1f,0f,0f,0.0313f,0f,1.0061f,0f,-0.5825f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_nose) {transformation: [-1f,0f,0f,0f,0f,0.98f,0f,-0.8275f,0f,0f,-1f,0.1875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_head) {transformation: [-1f,0f,0f,0.0313f,0f,0.98f,0f,-0.8887f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_left_arm) {transformation: [-0.9936f,0.1132f,0f,-0.3125f,0.1109f,0.9737f,0f,-0.95f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_right_arm) {transformation: [-0.9936f,-0.1132f,0f,0.3125f,-0.1109f,0.9737f,0f,-0.95f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_body) {transformation: [-1f,0f,0f,0.0313f,0f,0.98f,0f,-1.5625f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}