# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_left_foot) {transformation: [-1f,0f,0f,0.1563f,0f,0.97f,0f,-1.32f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_foot) {transformation: [-1f,0f,0f,-0.1562f,0f,0.97f,0f,-1.32f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_antenna) {transformation: [-1f,0f,0f,0.0313f,0f,1.0088f,0f,-0.5925f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_nose) {transformation: [-1f,0f,0f,0f,0f,0.97f,0f,-0.835f,0f,0f,-1f,0.1875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_head) {transformation: [-1f,0f,0f,0.0313f,0f,0.97f,0f,-0.8956f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left_arm) {transformation: [-0.9856f,0.1693f,0f,-0.3125f,0.1643f,0.956f,0f,-0.9562f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_arm) {transformation: [-0.9856f,-0.1693f,0f,0.3125f,-0.1643f,0.956f,0f,-0.9562f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body) {transformation: [-1f,0f,0f,0.0313f,0f,0.97f,0f,-1.5625f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}