# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.enderkin.root] run return 0
execute on passengers if entity @s[tag=aj.enderkin.data] unless data entity @s {data:{rigHash: 'ce588ec8e2a32bd803a5e00e974acedc4e7b6f4e1638c2358def46ed5a194113'}} on vehicle run function animated_java:enderkin/root/zzz/check_rig_hash
scoreboard players set @s aj.is_rig_loaded 1