# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.enderkin.root] run return 0
execute on passengers if entity @s[tag=aj.enderkin.data] unless data entity @s {data:{rigHash: 'ba5d0bb341abee5a499628d1f1305fabe0acbfe054a2423256c73fbe15ce80a6'}} on vehicle run function animated_java:enderkin/root/zzz/check_rig_hash
scoreboard players set @s aj.is_rig_loaded 1