# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
tag @s remove aj.dirt_golem.animation.plant.playing
scoreboard players set @s aj.plant.frame 0
tag @s add aj.transforms_only
execute at @s run function animated_java:dirt_golem/animations/plant/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only