# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers if entity @s[tag=aj.hedgehog.bone.leg_left_front] run data merge entity @s {transformation: [-1f,0f,0f,0.125f,0f,1f,0f,-0.3125f,0f,0f,-1f,0.125f,0f,0f,0f,1f], start_interpolation: -1}
execute on passengers if entity @s[tag=aj.hedgehog.bone.leg_right_back] run data merge entity @s {transformation: [-1f,0f,0f,-0.125f,0f,1f,0f,-0.3125f,0f,0f,-1f,-0.1875f,0f,0f,0f,1f], start_interpolation: -1}
execute on passengers if entity @s[tag=aj.hedgehog.bone.leg_right_front] run data merge entity @s {transformation: [-1f,0f,0f,-0.125f,0f,1f,0f,-0.3125f,0f,0f,-1f,0.125f,0f,0f,0f,1f], start_interpolation: -1}
execute on passengers if entity @s[tag=aj.hedgehog.bone.leg_left_back] run data merge entity @s {transformation: [-1f,0f,0f,0.125f,0f,1f,0f,-0.3125f,0f,0f,-1f,-0.1875f,0f,0f,0f,1f], start_interpolation: -1}
execute on passengers if entity @s[tag=aj.hedgehog.bone.head] run data merge entity @s {transformation: [-1f,0f,0f,0f,0f,1f,0f,-0.3125f,0f,0f,-1f,0f,0f,0f,0f,1f], start_interpolation: -1}
execute on passengers if entity @s[tag=aj.hedgehog.bone.top] run data merge entity @s {transformation: [-1f,0f,0f,0f,0f,1f,0f,-0.375f,0f,0f,-1f,0f,0f,0f,0f,1f], start_interpolation: -1}
execute on passengers if entity @s[tag=aj.hedgehog.bone.left] run data merge entity @s {transformation: [-1f,0f,0f,0f,0f,1f,0f,-0.375f,0f,0f,-1f,0f,0f,0f,0f,1f], start_interpolation: -1}
execute on passengers if entity @s[tag=aj.hedgehog.bone.right] run data merge entity @s {transformation: [-1f,0f,0f,0f,0f,1f,0f,-0.375f,0f,0f,-1f,0f,0f,0f,0f,1f], start_interpolation: -1}
execute on passengers if entity @s[tag=aj.hedgehog.bone.body] run data merge entity @s {transformation: [-1f,0f,0f,0f,0f,1f,0f,-0.375f,0f,0f,-1f,0f,0f,0f,0f,1f], start_interpolation: -1}
execute on passengers if entity @s[tag=aj.hedgehog.bone.top1] run data merge entity @s {transformation: [-1f,0f,0f,0f,0f,1f,0f,-0.375f,0f,0f,-1f,0f,0f,0f,0f,1f], start_interpolation: -1}
execute on passengers if entity @s[tag=aj.hedgehog.bone.left1] run data merge entity @s {transformation: [-1f,0f,0f,0f,0f,1f,0f,-0.375f,0f,0f,-1f,0f,0f,0f,0f,1f], start_interpolation: -1}
execute on passengers if entity @s[tag=aj.hedgehog.bone.right1] run data merge entity @s {transformation: [-1f,0f,0f,0f,0f,1f,0f,-0.375f,0f,0f,-1f,0f,0f,0f,0f,1f], start_interpolation: -1}
execute on passengers if entity @s[tag=aj.hedgehog.bone.front] run data merge entity @s {transformation: [-1f,0f,0f,0f,0f,1f,0f,-0.375f,0f,0f,-1f,0f,0f,0f,0f,1f], start_interpolation: -1}
execute on passengers if entity @s[tag=aj.hedgehog.bone.back] run data merge entity @s {transformation: [-1f,0f,0f,0f,0f,1f,0f,-0.375f,0f,0f,-1f,0f,0f,0f,0f,1f], start_interpolation: -1}
execute on passengers if entity @s[tag=aj.hedgehog.bone.ball] run data merge entity @s {transformation: [-1f,0f,0f,0f,0f,1f,0f,-0.375f,0f,0f,-1f,0f,0f,0f,0f,1f], start_interpolation: -1}