# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
tag @s remove aj.snail.animation.idle.playing
tag @s remove aj.snail.animation.walk.playing
tag @s remove aj.snail.animation.hide.playing
tag @s remove aj.snail.animation.exit_hide.playing