# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.bloomer.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'bloomer', 'function_path': 'animated_java:bloomer/variants/default_flash/apply'}
execute on passengers if entity @s[tag=aj.bloomer.bone.head] run function animated_java:bloomer/variants/default_flash/zzz/apply_to_bone_head
execute on passengers if entity @s[tag=aj.bloomer.bone.leg0] run function animated_java:bloomer/variants/default_flash/zzz/apply_to_bone_leg0
execute on passengers if entity @s[tag=aj.bloomer.bone.leg1] run function animated_java:bloomer/variants/default_flash/zzz/apply_to_bone_leg1
execute on passengers if entity @s[tag=aj.bloomer.bone.leg2] run function animated_java:bloomer/variants/default_flash/zzz/apply_to_bone_leg2
execute on passengers if entity @s[tag=aj.bloomer.bone.leg3] run function animated_java:bloomer/variants/default_flash/zzz/apply_to_bone_leg3
execute on passengers if entity @s[tag=aj.bloomer.bone.body] run function animated_java:bloomer/variants/default_flash/zzz/apply_to_bone_body
return 1