# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_head) {transformation: [-1.0116f,0f,0f,0f,0f,1f,0f,-0.5f,0f,0f,-1.0116f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_leg0) {transformation: [-1.0116f,0f,0f,-0.1265f,0f,1f,0f,-1.25f,0f,0f,-1.0116f,-0.2529f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_leg1) {transformation: [-1.0116f,0f,0f,0.1265f,0f,1f,0f,-1.25f,0f,0f,-1.0116f,-0.2529f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_leg2) {transformation: [-1.0116f,0f,0f,-0.1265f,0f,1f,0f,-1.25f,0f,0f,-1.0116f,0.2529f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_leg3) {transformation: [-1.0116f,0f,0f,0.1265f,0f,1f,0f,-1.25f,0f,0f,-1.0116f,0.2529f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_body) {transformation: [-1.0116f,0f,0f,0f,0f,1f,0f,-1.625f,0f,0f,-1.0116f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}