# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.tuff_golem.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'tuff_golem', 'function_path': 'animated_java:tuff_golem/variants/red_hurt/apply'}
execute on passengers if entity @s[tag=aj.tuff_golem.bone.head] run function animated_java:tuff_golem/variants/red_hurt/zzz/apply_to_bone_head
execute on passengers if entity @s[tag=aj.tuff_golem.bone.body] run function animated_java:tuff_golem/variants/red_hurt/zzz/apply_to_bone_body
execute on passengers if entity @s[tag=aj.tuff_golem.bone.clothing] run function animated_java:tuff_golem/variants/red_hurt/zzz/apply_to_bone_clothing
execute on passengers if entity @s[tag=aj.tuff_golem.bone.left_leg] run function animated_java:tuff_golem/variants/red_hurt/zzz/apply_to_bone_left_leg
execute on passengers if entity @s[tag=aj.tuff_golem.bone.nose] run function animated_java:tuff_golem/variants/red_hurt/zzz/apply_to_bone_nose
execute on passengers if entity @s[tag=aj.tuff_golem.bone.right_leg] run function animated_java:tuff_golem/variants/red_hurt/zzz/apply_to_bone_right_leg
execute on passengers if entity @s[tag=aj.tuff_golem.bone.left_arm] run function animated_java:tuff_golem/variants/red_hurt/zzz/apply_to_bone_left_arm
execute on passengers if entity @s[tag=aj.tuff_golem.bone.right_arm] run function animated_java:tuff_golem/variants/red_hurt/zzz/apply_to_bone_right_arm
execute on passengers if entity @s[tag=aj.tuff_golem.bone.display] run function animated_java:tuff_golem/variants/red_hurt/zzz/apply_to_bone_display
return 1