# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_shell) {transformation: [-1f,0f,0f,0f,0f,1f,-0.0087f,-0.2937f,0f,-0.0087f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body) {transformation: [-1f,0f,0f,0f,0f,1f,0.0087f,-0.2937f,0f,0.0087f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left_claw) {transformation: [-1f,0f,0f,0f,0f,0.9998f,-0.0175f,-0.2937f,0f,-0.0175f,-0.9998f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_claw) {transformation: [-1f,0f,0f,0f,0f,0.9998f,0.0175f,-0.2937f,0f,0.0175f,-0.9998f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left_legs) {transformation: [-1f,0f,0f,0f,0f,0.9998f,0.0175f,-0.2925f,0f,0.0175f,-0.9998f,0.0013f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_legs) {transformation: [-1f,0f,0f,0f,0f,0.9998f,-0.0175f,-0.2937f,0f,-0.0175f,-0.9998f,0.0013f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}