# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:vulture/animations/default/zzz/apply_frame {frame: 50}
scoreboard players add @s aj.default.frame 1