# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_leg_left_front) {transformation: [-0.9914f,-0.1305f,0f,0.125f,-0.1305f,0.9914f,0f,-0.2187f,0f,0f,-1f,0.125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg_right_back) {transformation: [-0.9914f,0.1305f,0f,-0.125f,0.1305f,0.9914f,0f,-0.2187f,0f,0f,-1f,-0.1875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg_right_front) {transformation: [-0.9914f,0.1305f,0f,-0.125f,0.1305f,0.9914f,0f,-0.2187f,0f,0f,-1f,0.125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg_left_back) {transformation: [-0.9914f,-0.1305f,0f,0.125f,-0.1305f,0.9914f,0f,-0.2187f,0f,0f,-1f,-0.1875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_head) {transformation: [-1f,0f,0f,0f,0f,0.999f,-0.0436f,-0.2187f,0f,-0.0436f,-0.999f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_top) {transformation: [-1f,0f,0f,0f,0f,1f,0f,-0.2812f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left) {transformation: [-1f,0f,0f,0f,0f,1f,0f,-0.2812f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right) {transformation: [-1f,0f,0f,0f,0f,1f,0f,-0.2812f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body) {transformation: [-1f,0f,0f,0f,0f,1f,0f,-0.2812f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_top1) {transformation: [-0.3f,0f,0f,0f,0f,0.3f,0f,-0.1875f,0f,0f,-0.3f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left1) {transformation: [-0.3f,0f,0f,0f,0f,0.3f,0f,-0.1875f,0f,0f,-0.3f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right1) {transformation: [-0.3f,0f,0f,0f,0f,0.3f,0f,-0.1875f,0f,0f,-0.3f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_front) {transformation: [-0.3f,0f,0f,0f,0f,0.3f,0f,-0.1875f,0f,0f,-0.3f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_back) {transformation: [-0.3f,0f,0f,0f,0f,0.3f,0f,-0.1875f,0f,0f,-0.3f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_ball) {transformation: [-0.3f,0f,0f,0f,0f,0.3f,0f,-0.1875f,0f,0f,-0.3f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}