# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_leg_left_front) {transformation: [-0.797f,-0.0697f,0f,0.1f,-0.0697f,0.797f,0f,-0.2312f,0f,0f,-0.7667f,0.0958f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_leg_right_back) {transformation: [-0.797f,0.0697f,0f,-0.1f,0.0697f,0.797f,0f,-0.2312f,0f,0f,-0.7667f,-0.1438f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_leg_right_front) {transformation: [-0.797f,0.0697f,0f,-0.1f,0.0697f,0.797f,0f,-0.2312f,0f,0f,-0.7667f,0.0958f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_leg_left_back) {transformation: [-0.797f,-0.0697f,0f,0.1f,-0.0697f,0.797f,0f,-0.2312f,0f,0f,-0.7667f,-0.1438f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_head) {transformation: [-0.8f,0f,0f,0f,0f,0.7997f,-0.0233f,-0.2312f,0f,-0.0223f,-0.7663f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_top) {transformation: [-0.8f,0f,0f,0f,0f,0.8f,0f,-0.2812f,0f,0f,-0.7667f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_left) {transformation: [-0.8f,0f,0f,0f,0f,0.8f,0f,-0.2812f,0f,0f,-0.7667f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_right) {transformation: [-0.8f,0f,0f,0f,0f,0.8f,0f,-0.2812f,0f,0f,-0.7667f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_body) {transformation: [-0.8f,0f,0f,0f,0f,0.8f,0f,-0.2812f,0f,0f,-0.7667f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_top1) {transformation: [-0.5333f,0f,0f,0f,0f,0.5333f,0f,-0.2552f,0f,0f,-0.5333f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_left1) {transformation: [-0.5333f,0f,0f,0f,0f,0.5333f,0f,-0.2552f,0f,0f,-0.5333f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_right1) {transformation: [-0.5333f,0f,0f,0f,0f,0.5333f,0f,-0.2552f,0f,0f,-0.5333f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_front) {transformation: [-0.5333f,0f,0f,0f,0f,0.5333f,0f,-0.2552f,0f,0f,-0.5333f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_back) {transformation: [-0.5333f,0f,0f,0f,0f,0.5333f,0f,-0.2552f,0f,0f,-0.5333f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_ball) {transformation: [-0.5333f,0f,0f,0f,0f,0.5333f,0f,-0.2552f,0f,0f,-0.5333f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}