# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_leg_left_front) {transformation: [-0.5994f,-0.0262f,0f,0.075f,-0.0262f,0.5994f,0f,-0.2437f,0f,0f,-0.5333f,0.0667f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg_right_back) {transformation: [-0.5994f,0.0262f,0f,-0.075f,0.0262f,0.5994f,0f,-0.2437f,0f,0f,-0.5333f,-0.1f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg_right_front) {transformation: [-0.5994f,0.0262f,0f,-0.075f,0.0262f,0.5994f,0f,-0.2437f,0f,0f,-0.5333f,0.0667f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg_left_back) {transformation: [-0.5994f,-0.0262f,0f,0.075f,-0.0262f,0.5994f,0f,-0.2437f,0f,0f,-0.5333f,-0.1f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_head) {transformation: [-0.6f,0f,0f,0f,0f,0.5999f,-0.0087f,-0.2437f,0f,-0.0078f,-0.5333f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_top) {transformation: [-0.6f,0f,0f,0f,0f,0.6f,0f,-0.2812f,0f,0f,-0.5333f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left) {transformation: [-0.6f,0f,0f,0f,0f,0.6f,0f,-0.2812f,0f,0f,-0.5333f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right) {transformation: [-0.6f,0f,0f,0f,0f,0.6f,0f,-0.2812f,0f,0f,-0.5333f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body) {transformation: [-0.6f,0f,0f,0f,0f,0.6f,0f,-0.2812f,0f,0f,-0.5333f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_top1) {transformation: [-0.7667f,0f,0f,0f,0f,0.7667f,0f,-0.3229f,0f,0f,-0.7667f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left1) {transformation: [-0.7667f,0f,0f,0f,0f,0.7667f,0f,-0.3229f,0f,0f,-0.7667f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right1) {transformation: [-0.7667f,0f,0f,0f,0f,0.7667f,0f,-0.3229f,0f,0f,-0.7667f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_front) {transformation: [-0.7667f,0f,0f,0f,0f,0.7667f,0f,-0.3229f,0f,0f,-0.7667f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_back) {transformation: [-0.7667f,0f,0f,0f,0f,0.7667f,0f,-0.3229f,0f,0f,-0.7667f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_ball) {transformation: [-0.7667f,0f,0f,0f,0f,0.7667f,0f,-0.3229f,0f,0f,-0.7667f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}