# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_leg_left_front) {transformation: [-0.4f,0f,0f,0.05f,0f,0.4f,0f,-0.2562f,0f,0f,-0.3f,0.0375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_leg_right_back) {transformation: [-0.4f,0f,0f,-0.05f,0f,0.4f,0f,-0.2562f,0f,0f,-0.3f,-0.0563f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_leg_right_front) {transformation: [-0.4f,0f,0f,-0.05f,0f,0.4f,0f,-0.2562f,0f,0f,-0.3f,0.0375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_leg_left_back) {transformation: [-0.4f,0f,0f,0.05f,0f,0.4f,0f,-0.2562f,0f,0f,-0.3f,-0.0562f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_head) {transformation: [-0.4f,0f,0f,0f,0f,0.4f,0f,-0.2562f,0f,0f,-0.3f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_top) {transformation: [-0.4f,0f,0f,0f,0f,0.4f,0f,-0.2812f,0f,0f,-0.3f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_left) {transformation: [-0.4f,0f,0f,0f,0f,0.4f,0f,-0.2812f,0f,0f,-0.3f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_right) {transformation: [-0.4f,0f,0f,0f,0f,0.4f,0f,-0.2812f,0f,0f,-0.3f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_body) {transformation: [-0.4f,0f,0f,0f,0f,0.4f,0f,-0.2812f,0f,0f,-0.3f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_top1) {transformation: [-1f,0f,0f,0f,0f,1f,0f,-0.3906f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_left1) {transformation: [-1f,0f,0f,0f,0f,1f,0f,-0.3906f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_right1) {transformation: [-1f,0f,0f,0f,0f,1f,0f,-0.3906f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_front) {transformation: [-1f,0f,0f,0f,0f,1f,0f,-0.3906f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_back) {transformation: [-1f,0f,0f,0f,0f,1f,0f,-0.3906f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_ball) {transformation: [-1f,0f,0f,0f,0f,1f,0f,-0.3906f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}