# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display_item_display) {transformation: [0f,0f,0f,0f,0f,0f,0f,-0.375f,0f,0f,0f,0.0625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_emissive_head) {transformation: [1f,0f,0f,0f,0f,0.9703f,0.2419f,-0.0369f,0f,-0.2419f,0.9703f,-0.095f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_head) {transformation: [1f,0f,0f,0f,0f,0.9703f,0.2419f,-0.0167f,0f,-0.2419f,0.9703f,-0.1f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_emissive_left_arm) {transformation: [0.866f,0.5f,0f,-0.4187f,-0.5f,0.866f,0f,-0.2167f,0f,0f,1f,-0.075f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_left_arm) {transformation: [0.866f,0.5f,0f,-0.4813f,-0.5f,0.866f,0f,-0.325f,0f,0f,1f,-0.075f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_emissive_right_arm) {transformation: [0.866f,-0.5f,0f,0.4188f,0.5f,0.866f,0f,-0.2167f,0f,0f,1f,-0.075f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_right_arm) {transformation: [0.866f,-0.5f,0f,0.4813f,0.5f,0.866f,0f,-0.325f,0f,0f,1f,-0.075f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}