# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers if entity @s[tag=aj.dirt_golem.bone.body] run function animated_java:dirt_golem/variants/default_hurt/zzz/apply_to_bone_body
execute on passengers if entity @s[tag=aj.dirt_golem.bone.left_leg] run function animated_java:dirt_golem/variants/default_hurt/zzz/apply_to_bone_left_leg
execute on passengers if entity @s[tag=aj.dirt_golem.bone.right_leg] run function animated_java:dirt_golem/variants/default_hurt/zzz/apply_to_bone_right_leg
execute on passengers if entity @s[tag=aj.dirt_golem.bone.left_arm] run function animated_java:dirt_golem/variants/default_hurt/zzz/apply_to_bone_left_arm
execute on passengers if entity @s[tag=aj.dirt_golem.bone.right_arm] run function animated_java:dirt_golem/variants/default_hurt/zzz/apply_to_bone_right_arm
execute on passengers if entity @s[tag=aj.dirt_golem.bone.hat] run function animated_java:dirt_golem/variants/default_hurt/zzz/apply_to_bone_hat
return 1