# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers if entity @s[tag=aj.glare.bone.head] run function animated_java:glare/variants/default/zzz/apply_to_bone_head
execute on passengers if entity @s[tag=aj.glare.bone.mid] run function animated_java:glare/variants/default/zzz/apply_to_bone_mid
execute on passengers if entity @s[tag=aj.glare.bone.lower] run function animated_java:glare/variants/default/zzz/apply_to_bone_lower
return 1