# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.vulture.root] run return 0
execute on passengers if entity @s[tag=aj.vulture.data] unless data entity @s {data:{rigHash: 'e8a46aec234f3d026db80776ef1ebdac79bfac31406e9b8589968ad7888c1a79'}} on vehicle run function animated_java:vulture/root/zzz/check_rig_hash
scoreboard players set @s aj.is_rig_loaded 1