# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers if entity @s[tag=aj.jellyfish.bone.body] run function animated_java:jellyfish/variants/cyan_hurt/zzz/apply_to_bone_body
execute on passengers if entity @s[tag=aj.jellyfish.bone.stingers_1] run function animated_java:jellyfish/variants/cyan_hurt/zzz/apply_to_bone_stingers_1
execute on passengers if entity @s[tag=aj.jellyfish.bone.stingers_2] run function animated_java:jellyfish/variants/cyan_hurt/zzz/apply_to_bone_stingers_2
execute on passengers if entity @s[tag=aj.jellyfish.bone.stingers_3] run function animated_java:jellyfish/variants/cyan_hurt/zzz/apply_to_bone_stingers_3
execute on passengers if entity @s[tag=aj.jellyfish.bone.stingers_4] run function animated_java:jellyfish/variants/cyan_hurt/zzz/apply_to_bone_stingers_4
return 1