# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.nautilus_crab.root] run return 0
execute on passengers if entity @s[tag=aj.nautilus_crab.data] unless data entity @s {data:{rigHash: '392edab2a7a62df578e1658bb4da569a2792ce735456409388ae4c8339dc2bdd'}} on vehicle run function animated_java:nautilus_crab/root/zzz/0
scoreboard players set @s aj.is_rig_loaded 1