# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.nautilus_crab.root] run return 0
execute on passengers if entity @s[tag=aj.nautilus_crab.data] unless data entity @s {data:{rigHash: '19ad0ff26a7c6dd3c205c0490ce8a70a684a55a0b942d02eb84d86c7799b3c1d'}} on vehicle run function animated_java:nautilus_crab/root/zzz/0
scoreboard players set @s aj.is_rig_loaded 1