# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
tag @s remove aj.cruncher.animation.idle.playing
tag @s remove aj.cruncher.animation.walk.playing
tag @s remove aj.cruncher.animation.fall.playing
tag @s remove aj.cruncher.animation.eat.playing