# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_head) {transformation: [-1.05f,0.009f,0f,0.0102f,0.0095f,1f,0f,-0.5f,0f,0f,-1.05f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_leg0) {transformation: [-1.05f,0.009f,0f,-0.1279f,0.0095f,1f,0f,-1.2488f,0f,0f,-1.05f,-0.2625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_leg1) {transformation: [-1.05f,0.009f,0f,0.1346f,0.0095f,1f,0f,-1.2512f,0f,0f,-1.05f,-0.2625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_leg2) {transformation: [-1.05f,0.009f,0f,-0.1279f,0.0095f,1f,0f,-1.2488f,0f,0f,-1.05f,0.2625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_leg3) {transformation: [-1.05f,0.009f,0f,0.1346f,0.0095f,1f,0f,-1.2512f,0f,0f,-1.05f,0.2625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_body) {transformation: [-1.05f,0.009f,0f,0f,0.0095f,1f,0f,-1.625f,0f,0f,-1.05f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}