# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_head) {transformation: [-1f,0f,0f,0f,0f,1f,-0.0087f,-1.1275f,0f,-0.0087f,-1f,0.0063f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_nose) {transformation: [-1f,0f,0f,0f,0f,1f,-0.0087f,-1.1275f,0f,-0.0087f,-1f,0.0063f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_left_arm) {transformation: [-1f,0.0052f,0f,0f,0.0052f,1f,0f,-1.125f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_right_arm) {transformation: [-1f,-0.0052f,0f,0f,-0.0052f,1f,0f,-1.125f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}