# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display_item_display) {transformation: [0f,0f,0f,0f,0f,0f,0f,-0.375f,0f,0f,0f,0.5625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_emissive_head) {transformation: [1f,0f,0f,0f,0f,1f,0f,-0.0625f,0f,0f,1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_head) {transformation: [1f,0f,0f,0f,0f,1f,0f,-0.0417f,0f,0f,1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_emissive_body) {transformation: [1f,0f,0f,0f,0f,1f,0f,-0.5625f,0f,0f,1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_body) {transformation: [1f,0f,0f,0f,0f,1f,0f,-0.5156f,0f,0f,1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_emissive_left_arm) {transformation: [1f,0f,0f,-0.4062f,0f,1f,0f,-0.375f,0f,0f,1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_left_arm) {transformation: [1f,0f,0f,-0.4062f,0f,1f,0f,-0.5f,0f,0f,1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_emissive_right_arm) {transformation: [1f,0f,0f,0.4063f,0f,1f,0f,-0.375f,0f,0f,1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_right_arm) {transformation: [1f,0f,0f,0.4063f,0f,1f,0f,-0.5f,0f,0f,1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}