# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:penguin/animations/fall/zzz/apply_frame {frame: 10}
scoreboard players add @s aj.fall.frame 1