# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers if entity @s[tag=aj.nautilus_crab.bone.shell] run function animated_java:nautilus_crab/variants/blue/zzz/apply_to_bone_shell
execute on passengers if entity @s[tag=aj.nautilus_crab.bone.body] run function animated_java:nautilus_crab/variants/blue/zzz/apply_to_bone_body
execute on passengers if entity @s[tag=aj.nautilus_crab.bone.left_claw] run function animated_java:nautilus_crab/variants/blue/zzz/apply_to_bone_left_claw
execute on passengers if entity @s[tag=aj.nautilus_crab.bone.right_claw] run function animated_java:nautilus_crab/variants/blue/zzz/apply_to_bone_right_claw
execute on passengers if entity @s[tag=aj.nautilus_crab.bone.left_legs] run function animated_java:nautilus_crab/variants/blue/zzz/apply_to_bone_left_legs
execute on passengers if entity @s[tag=aj.nautilus_crab.bone.right_legs] run function animated_java:nautilus_crab/variants/blue/zzz/apply_to_bone_right_legs
return 1