# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.rat.root] run return 0
execute if entity @s[tag=aj.rat.animation.idle.playing] at @s if entity @e[type=player,distance=..32] run function animated_java:rat/animations/idle/zzz/on_tick
execute if entity @s[tag=aj.rat.animation.walk.playing] at @s if entity @e[type=player,distance=..32] run function animated_java:rat/animations/walk/zzz/on_tick
execute if entity @s[tag=aj.rat.animation.eat.playing] at @s if entity @e[type=player,distance=..32] run function animated_java:rat/animations/eat/zzz/on_tick
#execute at @s on passengers run rotate @s ~ ~