# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=minecraft:item_display,tag=aj.enderkin.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'enderkin', 'function_path': 'animated_java:enderkin/variants/white/apply'}
execute on passengers if entity @s[tag=aj.enderkin.bone.emissive_head] run function animated_java:enderkin/variants/white/zzz/apply_to_bone_emissive_head
execute on passengers if entity @s[tag=aj.enderkin.bone.head] run function animated_java:enderkin/variants/white/zzz/apply_to_bone_head
execute on passengers if entity @s[tag=aj.enderkin.bone.emissive_body] run function animated_java:enderkin/variants/white/zzz/apply_to_bone_emissive_body
execute on passengers if entity @s[tag=aj.enderkin.bone.body] run function animated_java:enderkin/variants/white/zzz/apply_to_bone_body
execute on passengers if entity @s[tag=aj.enderkin.bone.emissive_left_arm] run function animated_java:enderkin/variants/white/zzz/apply_to_bone_emissive_left_arm
execute on passengers if entity @s[tag=aj.enderkin.bone.left_arm] run function animated_java:enderkin/variants/white/zzz/apply_to_bone_left_arm
execute on passengers if entity @s[tag=aj.enderkin.bone.emissive_right_arm] run function animated_java:enderkin/variants/white/zzz/apply_to_bone_emissive_right_arm
execute on passengers if entity @s[tag=aj.enderkin.bone.right_arm] run function animated_java:enderkin/variants/white/zzz/apply_to_bone_right_arm
execute on passengers if entity @s[tag=aj.enderkin.bone.right_leg] run function animated_java:enderkin/variants/white/zzz/apply_to_bone_right_leg
execute on passengers if entity @s[tag=aj.enderkin.bone.left_leg] run function animated_java:enderkin/variants/white/zzz/apply_to_bone_left_leg
return 1