# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_body) {transformation: [-1.015f,0f,0f,0f,0f,0.97f,0f,0f,0f,0f,-1.015f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_stingers_1) {transformation: [-1f,0f,0f,0f,0f,0.9998f,0.0196f,0.0084f,0f,0.0196f,-0.9998f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_stingers_2) {transformation: [-0.9998f,-0.0196f,0f,0f,-0.0196f,0.9998f,0f,0.0084f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_stingers_3) {transformation: [-1f,0f,0f,0f,0f,0.9998f,-0.0196f,0.0084f,0f,-0.0196f,-0.9998f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_stingers_4) {transformation: [-0.9998f,0.0196f,0f,0f,0.0196f,0.9998f,0f,0.0084f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}