# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_tail) {transformation: [-1f,0f,0f,-0.0312f,0f,1f,0f,-0.4312f,0f,0f,-1f,-0.2562f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_left_wing) {transformation: [-1f,0f,0f,-0.375f,0f,1f,0f,-0.55f,0f,0f,-1f,-0.0188f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_right_wing) {transformation: [-1f,0f,0f,0f,0f,1f,0f,-0.55f,0f,0f,-1f,-0.0187f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_left_foot) {transformation: [-1f,0f,0f,-0.25f,0f,1f,0f,-0.5812f,0f,0f,-1f,-0.0188f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_right_foot) {transformation: [-1f,0f,0f,0f,0f,1f,0f,-0.5812f,0f,0f,-1f,0.0438f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_head) {transformation: [-1f,0f,0f,-0.0469f,0f,1f,0f,-0.05f,0f,0f,-1f,0.0437f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_body) {transformation: [-1f,0f,0f,0f,0f,1f,0f,-0.55f,0f,0f,-1f,-0.0187f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(item_display_bartering_item) {transformation: [-0.1414f,0.1414f,0f,0f,0.1414f,0.1414f,0f,0.0188f,0f,0f,-0.2f,0.1875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}