# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_left_wing) {transformation: [-0.9962f,0.0872f,0f,-0.4049f,0.0872f,0.9962f,0f,-0.5118f,0f,0f,-1f,-0.0188f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_wing) {transformation: [-0.9962f,-0.0872f,0f,0.0417f,-0.0872f,0.9962f,0f,-0.541f,0f,0f,-1f,-0.0187f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left_foot) {transformation: [-1f,0f,0f,-0.25f,0f,1f,0f,-0.5688f,0f,0f,-1f,-0.0188f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_foot) {transformation: [-1f,0f,0f,0f,0f,1f,0f,-0.5688f,0f,0f,-1f,0.0438f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_head) {transformation: [-1f,0f,0f,-0.0469f,0f,0.9903f,-0.1392f,-0.0375f,0f,-0.1392f,-0.9903f,0.0437f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body) {transformation: [-1f,0f,0f,0f,0f,1f,0f,-0.5375f,0f,0f,-1f,-0.0187f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}