# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_left_wing) {transformation: [-0.9397f,0.342f,0f,-0.4944f,0.342f,0.9397f,0f,-0.3972f,0f,0f,-1f,-0.0188f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_right_wing) {transformation: [-0.9397f,-0.342f,0f,0.1667f,-0.342f,0.9397f,0f,-0.5139f,0f,0f,-1f,-0.0187f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_left_foot) {transformation: [-1f,0f,0f,-0.25f,0f,1f,0f,-0.5312f,0f,0f,-1f,-0.0188f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_right_foot) {transformation: [-1f,0f,0f,0f,0f,1f,0f,-0.5312f,0f,0f,-1f,0.0438f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_head) {transformation: [-1f,0f,0f,-0.0469f,0f,0.848f,-0.5299f,0f,0f,-0.5299f,-0.848f,0.0437f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_body) {transformation: [-1f,0f,0f,0f,0f,1f,0f,-0.5f,0f,0f,-1f,-0.0187f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(item_display_bartering_item) {transformation: [-0.1347f,0.1474f,0.0108f,0f,0.1167f,0.115f,-0.1147f,0.0797f,-0.0908f,-0.0709f,-0.1635f,0.1406f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}