# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_left_wing) {transformation: [-0.866f,0.5f,0f,-0.5542f,0.5f,0.866f,0f,-0.3208f,0f,0f,-1f,-0.0188f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_wing) {transformation: [-0.866f,-0.5f,0f,0.25f,-0.5f,0.866f,0f,-0.4958f,0f,0f,-1f,-0.0187f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left_foot) {transformation: [-1f,0f,0f,-0.25f,0f,1f,0f,-0.5063f,0f,0f,-1f,-0.0188f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_foot) {transformation: [-1f,0f,0f,0f,0f,1f,0f,-0.5063f,0f,0f,-1f,0.0438f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_head) {transformation: [-1f,0f,0f,-0.0469f,0f,0.7951f,-0.6065f,0.025f,0f,-0.6065f,-0.7951f,0.0437f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body) {transformation: [-1f,0f,0f,0f,0f,1f,0f,-0.475f,0f,0f,-1f,-0.0187f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_bartering_item) {transformation: [-0.0463f,0.1942f,0.0116f,0f,0.1521f,0.0436f,-0.1223f,0.325f,-0.1213f,-0.0195f,-0.1578f,0.1275f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}