# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.copper_golem.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'copper_golem', 'function_path': 'animated_java:copper_golem/variants/default/apply'}
execute on passengers if entity @s[tag=aj.copper_golem.bone.left_foot] run function animated_java:copper_golem/variants/default/zzz/0
execute on passengers if entity @s[tag=aj.copper_golem.bone.right_foot] run function animated_java:copper_golem/variants/default/zzz/1
execute on passengers if entity @s[tag=aj.copper_golem.bone.antenna] run function animated_java:copper_golem/variants/default/zzz/2
execute on passengers if entity @s[tag=aj.copper_golem.bone.nose] run function animated_java:copper_golem/variants/default/zzz/3
execute on passengers if entity @s[tag=aj.copper_golem.bone.head] run function animated_java:copper_golem/variants/default/zzz/4
execute on passengers if entity @s[tag=aj.copper_golem.bone.left_arm] run function animated_java:copper_golem/variants/default/zzz/5
execute on passengers if entity @s[tag=aj.copper_golem.bone.right_arm] run function animated_java:copper_golem/variants/default/zzz/6
execute on passengers if entity @s[tag=aj.copper_golem.bone.body] run function animated_java:copper_golem/variants/default/zzz/7