# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.data_data set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.bloomer.node.head] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_head set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.bloomer.node.leg0] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_leg0 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.bloomer.node.leg1] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_leg1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.bloomer.node.leg2] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_leg2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.bloomer.node.leg3] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_leg3 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.bloomer.node.body] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_body set from storage aj:uuid main.out