# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
tag @s remove aj.enderkin.animation.bartering.playing
scoreboard players set @s aj.bartering.frame 0
tag @s add aj.transforms_only
execute at @s run function animated_java:enderkin/animations/bartering/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only