# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.pufftail.root] run return 0
execute if entity @s[tag=aj.pufftail.animation.idle.playing] run function animated_java:pufftail/animations/idle/zzz/on_tick
execute if entity @s[tag=aj.pufftail.animation.fly.playing] run function animated_java:pufftail/animations/fly/zzz/on_tick
#execute at @s on passengers run rotate @s ~ ~