# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_body) {transformation: [-1.0007f,0f,0f,0f,0f,1.0007f,0f,-0.1875f,0f,0f,-1.0007f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_head) {transformation: [-1f,0.0004f,0.004f,0f,0.0003f,1f,-0.0039f,-0.1875f,-0.004f,-0.0039f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_1) {transformation: [-0.9998f,0f,-0.0204f,0.0025f,0f,1f,0f,-0.1875f,0.0204f,0f,-0.9998f,0.0004f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_2) {transformation: [-1f,0f,0.0012f,-0.0017f,0f,1f,0f,-0.1875f,-0.0012f,0f,-1f,0.0005f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_3) {transformation: [-0.9995f,0f,-0.032f,0.0067f,0f,1f,0f,-0.1875f,0.032f,0f,-0.9995f,0.0008f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_4) {transformation: [-1f,0f,-0.0058f,-0.0012f,0f,1f,0f,-0.1875f,0.0058f,0f,-1f,0.0017f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}