# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.pufftail.root] run return 0
execute on passengers if entity @s[tag=aj.pufftail.data] unless data entity @s {data:{rigHash: '40a688f73bc743b1d958e5ac6a9f70f1a2d09d055295ced29c157782c9a014f1'}} on vehicle run function animated_java:pufftail/root/zzz/0
scoreboard players set @s aj.is_rig_loaded 1