# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.pufftail.root] run return 0
execute on passengers if entity @s[tag=aj.pufftail.data] unless data entity @s {data:{rigHash: '69dda2c52cc427f42fc625a1fadb419789e77377fbcaae1c0f57cc3c10bfd93c'}} on vehicle run function animated_java:pufftail/root/zzz/0
scoreboard players set @s aj.is_rig_loaded 1