# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.glare.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'glare', 'function_path': 'animated_java:glare/variants/pale_hurt/apply'}
execute on passengers if entity @s[tag=aj.glare.bone.head] run function animated_java:glare/variants/pale_hurt/zzz/0
execute on passengers if entity @s[tag=aj.glare.bone.mid] run function animated_java:glare/variants/pale_hurt/zzz/1
execute on passengers if entity @s[tag=aj.glare.bone.lower] run function animated_java:glare/variants/pale_hurt/zzz/2