# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
scoreboard objectives add aj.idle.frame dummy
scoreboard objectives add aj.idle_angry.frame dummy
scoreboard objectives add aj.walk.frame dummy
scoreboard objectives add aj.walk_angry.frame dummy
scoreboard objectives add aj.action.frame dummy