# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_head) {transformation: [-1f,0f,0f,0f,0f,1f,0f,-1.125f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body) {transformation: [-1f,0f,0f,0f,0f,1f,0f,-0.2812f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_clothing) {transformation: [-1f,0f,0f,0f,0f,1f,0f,-1.125f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left_leg) {transformation: [-1f,0f,0f,0f,0f,1f,0f,-1.125f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_nose) {transformation: [-1f,0f,0f,0f,0f,1f,0f,-1.125f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_leg) {transformation: [-1f,0f,0f,0f,0f,1f,0f,-1.125f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left_arm) {transformation: [-1f,0f,0f,0f,0f,0.3827f,-0.9239f,-0.825f,0f,-0.9239f,-0.3827f,0.5625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_arm) {transformation: [-1f,0f,0f,0f,0f,0.3827f,-0.9239f,-0.8187f,0f,-0.9239f,-0.3827f,0.5625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_tuff_golem_holding) {transformation: [-0.5f,0f,0f,0f,0f,0.5f,0f,-0.375f,0f,0f,-0.5f,0.625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_display) {transformation: [-1f,0f,0f,0f,0f,1f,0f,0f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}