# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.data_data set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.nautilus_crab.node.shell] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_shell set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.nautilus_crab.node.body] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_body set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.nautilus_crab.node.left_claw] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_left_claw set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.nautilus_crab.node.right_claw] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_right_claw set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.nautilus_crab.node.left_legs] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_left_legs set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.nautilus_crab.node.right_legs] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_right_legs set from storage aj:uuid main.out